- CondorMonitoring/JobCounter.py
This adds the tier0 pool to the collectors list.
Also updates the relval and test agents list
@julianbadillo please have a look
@amaltaro has the test agents list changed? I guess those old machines are no longer used
> Add tier0 collector to condor monitoring

- CondorMonitoring/JobCounter.py
It looks like this is one of the flocking configuration consequences
> A fix for double counting jobs in the tier0 pool and the global pool

- CondorMonitoring/JobCounter.py
Some test jobs or dev jobs dont have all the classadds that the monitoring script needs to account them
Ignore jobs like this for now.
> Handle jobs not coming from WMAgent

- resubmit.py
As discussed with Dima, he only wants to know the original workflow from which a clone was created (not the real first workflow injected into the system for that prepId/etc).
> Add the original request name to clones

- resubmit.py
@julianbadillo @ticoann I tested clones with OriginalRequestName and this view works like a charm
https://cmsweb-testbed.cern.ch/couchdb/reqmgr_workload_cache/_design/ReqMgr/_view/byoriginalrequest
@drkovalskyi , "key" is the original request and "value" (or "id") is the new one (clone)
> Adapt resubmit to OriginalRequestName

- assign.py
- condor_overview2.py
Added new script, assign.py, which merges the functionality of assignWorkflow.py and assignProdTaskChain.py.
> add merged scripts

- reject.py
- resubmit.py
Modified reject.py and resubmit.py to add --memory option to change the memory of the workflow. Tested resubmit.py using backfill jobs to make sure workflow memory is assigned as expected both with and without the option. MaxRSS will be set at assignment to Memory*1024 by the request manager client.
> Add option to change memory in reject.py and resubmit.py

- assign.py
- reject.py
- resubmit.py
Several changes to assign.py, including reverting back to the correct way to determine if we are dealing with a merge task when setting era and proc string. Other changes include setting sites using siteInfo class if --site "t1" or "t2" is given, and allowing the user to pass a comma-separated list of sites.
Added option to set max memory in reject.py and resubmit.py. These should be identical to the changes originally submitted in https://github.com/CMSCompOps/WmAgentScripts/pull/149
> More fixes to assign.py, redo memory option in reject.py and resubmit.py

- Unified/go_condor.py
- Unified/job_router_modules/unified_utils.py
Includes code for a single route for all overflow jobs, but that isn't
enabled.  For now, just combine sufficiently similar routes.
Reduces the amount of work the JobRouter has to do by about 2-3x.  Once we get the 'master overflow rule' working, it'll be an additional 2-3x (about an order of magnitude combined).
> Start overhaul of overflow routes.

- README.rst
- Unified/README.rst
Here's an example of how to make a README that Sphinx can turn into a webpage. This won't go on the central webpage until the README is in the CMSCompOps/WmAgentScripts repository, but here is an example of what the current README would turn into: http://t3serv001.mit.edu/~dabercro/wmagent_example/wmagentscripts.html.
Let me know if I should try to reproduce the information on the Twikis faithfully or if there is a smaller list of scripts that people are still using. I'm also more than happy to answer any questions about the examples in this PR and anything else about the central documentation: http://cms-comp-ops-tools.readthedocs.io/en/latest/
> Created README.rst to run Sphinx on.

- issues/getdataTaskChains.py
- reject.py
- reqMgrClient.py
- resubmit.py
- test/test_reqMgrClient.py
This PR is about adding the clone API, here:
https://github.com/CMSCompOps/WmAgentScripts/compare/master...amaltaro:clone-api?expand=1#diff-3fc98fbeeaadf6df0cfbc50d59551ffeR1120
one can simply provide the request name in the URI and that workflow gets cloned. Or one can provide a encoded python dictionary to be used to override arguments. This also works for overriding only one or two arguments inside a task/step.
Additional changes are:
* use reqmgr2 request api to retrieve the request json
* dropped access to the couchdb workfload_cache data (the same data as above)
* dropped the WMWorkload helper object from some places (need to be well tested). Can someone please clarify why it has to get the workload instance instead of just using the json request?
We still need to distinguish plain …
> Added clone API; fixed some wf submission code

- Unified/go_condor.py
- Unified/job_router_modules/unified_utils.py
Somehow along the lines of what you suggested @bbockelm 
The agents are already removing the draining sites from site whitelist.
The purpose here is a dramatic increase in number of failures is observed for a give site to go and quickly edit it out from the whitelist, with the possibility of adding it back just as quickly.
FYI @thongonary @mcremone
> hook to hold sites

- Unified/actor.py
- Unified/checkor.py
- Unified/completor.py
- campaignsConfiguration.py
- utils.py
- wtcActions.py
goes in the direction of #360 . @sharad1126 you should get used to the command line tool.
there are some cleanup to be finalized so that we delete elements from the db when the workflow(s) go out of scope
> HBF interface

- Unified/addHoc.py
- Unified/rulor.py
- Unified/showError.py
- utils.py
> Report in mongo

- utils.py
Confirmation from PPD
> Imagine we want to generate 10 events (each has 5 s time/event) and the request has filter efficiency of 0.5. Sample will actually produce 20 events and the time/event has no correction (still 5s and not 5s / 0.5)
So if the target time limit is 100 sec, the `max_events_per_lumi` allowed is (time limit) / (time per event) = 100/5 = 20 events, which will give 10 events in the output lumi. (This is what the PR is proposing.)
If we allow `max_events_per_lumi` to be divided by `efficiency_factor` like it has been currently, we will let `max_events_per_lumi` to be 100/5/0.5 = 40 events, which will take 200 secs to finish, ie, double the limit.
> Correct events per lumi based on time per event

- Unified/showError.py
Fixes the issue for manually adding 2 after the seeworkflow on opening the console.
ready
The console has two sub urls: seeworkflow and seeworkflow2. seeworkflow2 was made inorder to see that the deadlock doesn't occur and we don't get the 404 error page that we often get with seeworkflow. The other console links are never used as the new console never got ready to be used till now, so we can comment out those for now.
yes
@thongonary can you please have a look?
> Change console link from seeworkflow->seeworkflow2 and comment other consoles.

- campaigns.json
Removes T3_US_NERSC from blacklist for all campaigns.
ready
NERSC admins have made a check to avoid the issue. Removing the site from blacklist for all campaigns. 
yes
none
takes place once it is loaded into the mongodb
@sharad1126
> removed T3_US_NERSC from black lists.

- remove_campaign.py
Feature to remove campaign from mongodb, and campaigns.json and copy to archive_campaigns.json
tested and ready 
The script helps to remove the unwanted campaign from the mongodb,campaigns.json and copy it to archive_campaigns.json.
yes
https://github.com/CMSCompOps/WmAgentScripts/pull/430
needs campaigns.json, archive_campaigns.json and campaignsConfiguration.py 
@thongonary @optimisticcynic can you please have a look?
> script to remove campign and put in archive

- campaigns.json
Fixes issue of too many unwanted(not needed anymore) campaigns.
ready
The JSON file has been changed with all the campaigns that were listed by PPD in https://docs.google.com/document/d/1NWp4rhDiZAJ4c9YCGaPVRjMQgwhfWaJvUpB8Yq7RNQ4/edit?ts=5d0b337e#
except for HINPbPbAutumn18DRHiMix that doesn't exist in our configs(no JIRA and no wfs submitted with this campaign name).
yes, unless it's not put into the campaigns' configuration in the MongoDB. 
none
the JSON file needs to be loaded into the MongoDB to make changes in the system. 
@thongonary can you please have a look?
@optimisticcynic FYI
> Change json file with campaigns provided by PPD

- Unified/actor.py
Fixes job splitting issue for lumibased
ready
checks and sends critical log message if job splitting in LumiBased.
yes
N/A
no
@thongonary
> checking event splitting in lumibased

- JIRAClient.py
https://github.com/CMSCompOps/WmAgentScripts/issues/454
ready
Reinstalling the packages whenever `import jira` failed. This might be a dangerous practice, but a quick and dirty solution for now -- unless we have a more elegant way to handle this.
YES
What it does is essentially
```
sudo yum remove python-requests python-urllib3
sudo pip uninstall urllib3 requests
sudo pip install urllib3==1.25.6 requests==2.22.0 chardet==3.0.2
```
@amaltaro @drkovalskyi @sharad1126
> Quick fix for JIRA import failures

- utils.py
ready
name in https://cms-unified.web.cern.ch/cms-unified/showlog/?search=critical&module=componentInfo 
y
> component timing-out in critical messsage

- Unified/batchor.py
- Unified/closor.py
- campaignAPI.py
- campaignsConfiguration.py
Fixes https://github.com/dmwm/WMCore/issues/9310
not-tested
Summary of changes is:
* migrate from optparse to argparse (the former is not supported in python3)
* client APIs to interact with ReqMgr2 `campaignconfig` API.
* function to parse MongoDB campaign records and return WMCore formatted campaigns
* minor reorganization of the current campaignsConfiguration.py script
* then added a few extra methods such that we can reproduce MongoDB actions against CouchDB (ReqMgr2)
* updated `batchor` module to create (and delete) the same campaigns it updates in MongoDB.
* updated `closor` to delete campaigns in CouchDB as well
The usage of that script remains the same, same options and so on. The only difference is that it will try to make the same changes on two different backends, first MongoDB …
> APIs to campaign configuration in ReqMgr2; updated Ops campaign script

- Unified/batchor.py
Complement to #466 (read a bug fix for)
not-tested
Sharad reported this batchor crash over slack
```
File "Unified/batchor.py", line 154, in <module>
batchor(url)
File "Unified/batchor.py", line 85, in batchor
wmcoreCamp = parseMongoCampaigns(campaign)
File "/data/unified/WmAgentScripts/campaignAPI.py", line 132, in parseMongoCampaigns
conf[wmKey] = rec.get(uniKey, conf[wmKey])
AttributeError: 'unicode' object has no attribute 'get'
```
The previous PR was passing a plain string (campaign name) to the function to parse a unified campaign dictionary to a wmcore dictionary.
So this PR should be passing the correct data structure (with the `name` key/value pair), which will then be converted to a WMCore campaign schema.
yes
Bugfix for #466 
none
@sharad1126 @thongonary could one of you …
> Parse correct campaign config in batchor, for wmcore format

- .gitignore
No issue created
ready
Just so my `.idea` meta files (from the PyCharm IDE) don't get added to my commits.
yes
none
none
@sharad1126 please merge it at your convenience.
> Added .idea to the list of ignored files

- campaignAPI.py
Fixes #466 and #468
not-tested
There is still a problem in the code, sorry!
Problem is that when we parse the MongoDB campaign and create a WMCore one, the `parse` method returns a list of dictionaries. We were then passing it over to the `createCampaignConfig` method that was dealing with it as a dictionary (but it was a list of one dict).
This should fix that problem. If a list of multiple campaigns (multiple dicts) is passed in, the createCampaignConffig will report an error.
yes
Said in the first line, it's a bug fix for #466 and #468
none
@sharad1126 hoping it to be the last PR now.
> Accept list with a single campaign config in the createCampaignConfig method

- Unified/batchor.py
Complement to #471 
not-tested
I missed that print statement. Problem is that the print has data like [{...}], so it crashes when looking up for a key `CampaignName` in a list data type... sorry!
yes
#471 
none
@sharad1126
> get campaign dict from a list

- utils.py
as @amaltaro  knows already, many wqe are null in GQ (and that's really bad).
here to protect and prevent things from crashing
> null wqe are removed

- assigncycle.sh
Fixes 
nothing
Ready 
Limit to O(10) workflows per cycle so Alan can watch and debug.
Yes
https://github.com/CMSCompOps/WmAgentScripts/pull/473
@amaltaro @jenimal
> assign only 10 wfs per cycle for debugging

- Unified/checkor.py
Fixes https://cms-unified.web.cern.ch/cms-unified/showlog/?search=task_HIG-RunIISummer19UL17wmLHEGEN-00496 output to be set valid ("announce") with a duplicates and filemismatch
> No announce with duplicates

- unifiedConfiguration.json
- utils.py
This PR allows to do TaskChain to StepChain conversion based on the expected CPU inefficiency, which is computed as the average of wall-clock time CPU inefficiency. The efficiency estimation is most likely too conservative since some steps can benefit from extra cores even if max number of cores is not optimal. For now the threshold is set to 75%.
> TaskChain to StepChain conversion improvement

- utils.py
Apparently in some cases the information may not be available to compute what we need or it can be of a  wrong type. So in case of an exception set a flag that "efficiency" is not good to convert.
> protection against missing information

- JIRAClient.py
- Unified/checkor.py
with regards to https://its.cern.ch/jira/browse/CMSCOMPPR-11343 if one wants to avoid having to operate manually, see this PR.
adding a "cmsunified please do force-complete wfname" or "cmsunified please do bypass wfname" will result in the desired action
> force-complete and bypass directly from jira

- utils.py
with regards to 
https://hypernews.cern.ch/HyperNews/CMS/get/comp-ops/4856.html 
https://its.cern.ch/jira/browse/CMSCOMPPR-11171 
https://cms-unified.web.cern.ch/cms-unified/showlog/?search=ReReco-Run2018A-SingleMuon-12Nov2019_UL2018-0001&module=transferor&limit=500&size=10000
> The input is either fully in place or getting in full somewhere with [2000338]
> latches on existing transfers, and nothing else, settin staging
> setting pgunnell_Run2018A-v1-SingleMuon-12Nov2019_UL2018_1064p1_191114_160444_8742 status to staging
only request for AnalysisOps and DataOps should be considered as good source for production
> only pick requests for dataops and anaops

- Unified/htmlor.py
Fixes errors in htmlor logs:
```
sort: cannot read: 6: No such file or directory
grep: write error: Broken pipe
```
tested
htmlor module logs shows errors due to some mistakes in code. 
NO
#489 
sort -f
@z4027163
> htmlor code with legacy mistakes

- acrontab.list
Fixes #497 
ready
There is no acron connection to vocms0274 as per puppet and therefore no acron job can ever run on the machine. 
yes
n/a
acron 
@vlimant @z4027163 @jenimal
> Cleanlog Script issue

- utils.py
for #501 and more.
for any doc for which the getter is failing, the last doc in cache will be used, even if expired.
a critical message is send anyways on failing to retrieve a fresh doc.
> docCache gets last cached doc

- campaigns.json
- recoverMissingLumis.py
Fixes #509 
tested
WmAgent now depends on CRIC instead of siteDB. The dependency in the script now depends on CRIC too. 
no
CRIC, sitedb
@amaltaro fyi
> updating the recovermissinglumi script as per wmagent updates

- recoverMissingLumis.py
Fixes #509 
tested
WmAgent now depends on CRIC instead of siteDB. The dependency in the script now depends on CRIC too.
no
#512 
CRIC, sitedb
> updating the recovermissinglumi script as per wmagent update

- Unified/closor.py
- campaigns.json
- utils.py
Removed old legacy code from closor
not tested
```DDMCopies``` parameter is not used in campaigns at all. So we should remove this from production. 
yes
campaigns.json 
@z4027163
> Remove more legacy

- Unified/assignor.py
- Unified/injector.py
- Unified/transferor.py
Fixes https://github.com/dmwm/WMCore/issues/9527
tested
This is the first step towards migrating the data management logic out of Unified umbrella (and instead rely on the WMCore MicroServices for that).
This patch was supposed to simply disable the input data placement made in the transferor module, but nothing is just... and I noticed that the assignor module has A LOT of data location/presence as well.
A summary for the transferor changes is:
* forced the transferor module to set workflows to "staged" (in the Unified database/oracle)
* force the transferor module to `execute=False`, such that no phedex subscription requests will be made
* still let the module run in dry-run mode, such that we can see what would be the phedex requests
A summary of the assignor changes is:
* removed all …
> Remove all input data placement; force transferor to set wflows to staged

- utils.py
simple check on https://cmsweb.cern.ch/reqmgr2/data/info instead of adhoc workflows
> proper check on reqmgr

- utils.py
Fixes  (is there any issue for this?)
not-tested
Handle cases where one of those keys (e.g. `status`) is missing.
Just a note, if we have many tasks to be recovered within the same workflow, it appears to me that we would make that wmstatsserver call many times. That query is heavy and it should be avoided as much as we can (thus, single query for the workflow and handle multiple tasks on the client side).
yes
none
none
@sharad1126
> Fix KeyError exception while fetching failures from wmstatsserver

- Unified/htmlor.py
Fixes #536 
tested
As we already stopped stagor module in #537 , htmlor shouldn't check the stagor module locks and if it is running or not and not throw any heartbeats like
```
The module stagor has not ran in 12 hours, now 1 [d]2 [h] 4 [m] 47 [s]
```
no
#537 
@z4027163 @amaltaro
> remove stagor checks

- Unified/injector.py
Fixes #535 
tested
changed the status of the workflow from considered to staged should stop making transferor pick up the requests which are step-chain converted.
no
transferor.py 
@amaltaro @z4027163
> avoid sending stepchain workflows to transferor

- Unified/htmlor.py
Fixes #550 
tested
Remove the module check from htmlor so it doesn't complains about the module not able to run. 
no
#551 
htmlor, transferor
@amaltaro @z4027163
> remove transferor checks from htmlor

- utils.py
Fixes #557 
In development 
Added a try catch block and not change priority by % if failed jobs aren't found. shouldn't fail the module. 
no
#515 
wmstats server
@z4027163
> actor shouldn't fail because of not able to get failed jobs

- shortcycle.sh
Addition to #495 
tested
adding mappor module to acron jobs before equalizor
no
#495 
acron, shortcycle.sh
@vlimant @z4027163 fyi
> mappor added to run before equalizor

- Unified/closor.py
- unifiedConfiguration.json
Fixes #545 
not-tested
Adding  a check for ParentageResolved before announcement
YES 
https://github.com/dmwm/WMCore/pull/9657
No
@vlimant @sharad1126 @amaltaro
> Adding  a check for ParentageResolved before announcement

- serviceConfiguration.json
- utils.py
Read all configs in utils.py from serviceConfiguration.json
Fixes #542
not-tested
Exposing all the parameters related to service runtime environment to a separate file which should be excluded when merging `testing` -> `master` branches.
NO
No
No
@sharad1126  @vlimant
> Add paramenter configFile to the unifiedConfiguration class.

- Unified/assignSchema.py
- Unified/cachor.py
when oracle is completely out, module won't crash but would raise a "cmsr is not available" critical message.
merge-able right away IMO
> Oracle downtime

- Unified/batchor.py
Fixes #564 
ready
Changes site whitelist for HIN relvals from KIT and N2P3 to only CERN.
no, because all input data for HIN Relvals will now be available only at CERN disk. Request made to PdMv and DM team.
N/A
Input data required by relvals
@z4027163 @amaltaro fyi
> run HIN relvals only at CERN

- utils.py
Fixes #
not-tested
Given that CouchDB and wmstatsserver were working properly during the oracle outage (aka. no or very few clients sending requests). I'd like to test a new theory: where OSDroid and Unified queries are contributing to the couchdb and wmstats saturation and eventually unresponsiveness.
None of the calls to wmstatsserver are going through anyways, so if we can test this patch in for a couple of hours, at least, it would be great. I can create a "Revert" PR once this gets merged
From one of the cmsweb frontends, I see that these nodes are making requests to wmstats:
vocms0269
vocms0272
vocms0268
vocms0273
yes
none
none
@sharad1126 @z4027163
> Temporarily stop heavy wmstatsserver requests

- utils.py
Fixes #493 
tested
remove legacy gwmsmon calls which are not used. 
no
n/a
http://cms-gwmsmon.cern.ch/totalview//json/site_summary
@z4027163 @amaltaro fyi
> gwmsmon links not used anymore

- RucioClient.py
- Unified/RucioClient.py
- Unified/checkor.py
- phedexClient.py
Fixes #560 
tested
Adding a simple wrapper class of the Rucio Client so that we can safely replicate the set of checks done through Phedex and create a default fallback mechanism to Rucio, when it comes to NANOAOD data tiers. 
YES 
N/A
Requires:                                                                                                                  
> rucio-client          
Configuration file:
```
~/.local/etc/rucio.cfg
[common]
[client]
rucio_host = http://cms-rucio.cern.ch
auth_host = https://cms-rucio-auth.cern.ch
auth_type = x509
ca_cert = /etc/grid-security/certificates/
client_cert = $X509_USER_CERT
client_key = $X509_USER_KEY
client_x509_proxy = $X509_USER_PROXY
request_retries = 3
```
Environment: …
> Adding Rucio to DBS-Phedex consistency check

- postcycle-review-manual.sh
- postcycle-review-recovering.sh
- postcycle-strict.sh
- postcycle-update.sh
Fixes #560 
ready
`export RUCIO_HOME=~/.local/` is required to get the rucio.cfg file in-order to run the rucio client
yes
#561 
~/.local/etc/rucio.cfg
Content:
```
~/.local/etc/rucio.cfg
[common]
[client]
rucio_host = http://cms-rucio.cern.ch
auth_host = https://cms-rucio-auth.cern.ch
auth_type = x509
ca_cert = /etc/grid-security/certificates/
client_cert = $X509_USER_CERT
client_key = $X509_USER_KEY
client_x509_proxy = $X509_USER_PROXY
request_retries = 3
```
@amaltaro @ericvaandering @todor-ivanov
> added rucio export path

- utils.py
Fixes https://github.com/dmwm/WMCore/issues/9722
ready
check agentjobinfo is not null and let the function to check failed jobs fail gracefully 
yes
wmstats server
@z4027163 @amaltaro @todor-ivanov this should fix the issue.
> check agentjobinfo before searching in it

- utils.py
Fixes #578 
ready
changes the syntax of eoscp to the one as suggested by eos team. 
no
#312 
eos
@z4027163
> Fix eoscp syntax

- Unified/rejector.py
ready
* Add a test mode to check schema changes without committing any changes.
* Enforce single-core for StepChain conversions if a corresponding task in TaskChain is single-core
YES
@sharad1126, @amaltaro, @z4027163
> Rejector update

- unifiedConfiguration.json
Fixes #560 
ready
As per @amaltaro 's  request, I have added the NANOAOD tiers to non relval config too. 
no
#562 #561 
wmagents and rucio
@z4027163 @amaltaro @todor-ivanov
> add nanoaod to nonrelval for rucio too

- Unified/closor.py
Fixes #583 
ready
The sendLog function has two parameters and the log should go to the workflow logs instead of the normal closor logs. 
no
#584 
elastic-search
@amaltaro @todor-ivanov @z4027163
> should send log to closor module in the workflow log

- unifiedConfiguration.json
Fixes #589 
ready
Added NANOAOD and NANOAODSIM to tiers_with_no_custodial so that unified stops sending nanoaod to tape.
no
#562 #561 
n/a
@amaltaro @vlimant @nsmith- @todor-ivanov
> stop sending NANOAOD to tape from unified

- RucioClient.py
"fixes" #588 
rucio returned 
> (u'/Wprimetotb_M2000W600_LH_TuneCP5_13TeV-madgraph-pythia8/RunIISummer16NanoAODv7-PUMoriond17_Nano02Apr2020_102X_mcRun2_asymptotic_v8-v1/NANOAODSIM#04ef69e5-9084-4649-89d7-8ce9552f786f', None)
for the block length.
BTW: rucio setup could be more integrated
> Invalid rucio block lenght

- .github/workflows/check_shell_script.yml
ready
Add github actions for shell check.
yes
To be merged after #594 
No
> Add github actions for shell check

- .github/workflows/jsonlint.yml
ready
add github actions for jsonlint
Yes
To be merged after #598 
None
> add json lint actions

- Unified/assignor.py
Fixes #601 
ready
check the primary and then assign primary_aaa even if primary_aaa is in the campaign config.
no
N/A
N/A
@amaltaro this should fix what you asked us. @z4027163 fyi
> check primary dataset before assigning primary_aaa

- cWrap.sh
change mkdir in eos as suggested by eos team.
@sharad1126
> change eos mkdir

- cWrap.sh
- utils.py
Fixes eos processes getting stuck with D state. 
ready
added the env for eos as suggested by the eos team in https://cern.service-now.com/service-portal?id=ticket&table=incident&n=INC2457548
no
#581 
eos
@z4027163 fyi
> change eos cp and eos mkdir as per eosteam

- unifiedConfiguration.json
Adding GEN-SIM-DIGI-RAW-MINIAOD to unified configuration
ready
Phat and PdMv has requested to add a new data tier - GEN-SIM-DIGI-RAW-MINIAOD and as it would be an output dataset, the tier needs to go to DDM.
yes
N/A
DBS
@amaltaro @z4027163 @todor-ivanov fyi
> add GEN-SIM-DIGI-RAW-MINIAOD data tier to_DDM

- utils.py
Fixes #585 
An alternative way to tag pilot workflows besides "pilot" processing string, in order to have the normal output dataset name.
@sharad1126 @amaltaro
> Add alternative pilot from SubRequestType

- .github/workflows/check_shell_script.yml
- .github/workflows/check_shell_script_on_push.yml
Ready. Tested on my branch [here](https://github.com/ishanrai05/WmAgentScripts/pull/2)
I added a review bot that will comment on the line with the lint error and link to how to solve it. It only works on changed lines.
Yes
@sharad1126 @amaltaro
> add review dog with shell check

- .github/workflows/python_lint.yml
ready
Pylint will show errors only now.
Yes
@sharad1126 @amaltaro
> Give detailed report of pylint test failures

- Unified/assignor.py
print out available "space" after the site_out selection. Since PIC is full and unified is still assigning WFs to PIC.
> Add a print text for SITE choice

- unifiedConfiguration.json
Adds FNAL back to High PU relvals
ready
As discussed in the comp-ops meeting today, we are adding FNAL back to the site whitelist here. 
yes
n/a
FNAL
@z4027163 fyi
> added FNAL to high PU relval

- unifiedConfiguration.json
As discussed in yesterday's compops meeting. 
ready
HighPU to be run only at FNAL. 
yes
#620 
Purdue and Nebraska
@z4027163 fyi
> remove Nebraska and Purdue from HighPU relval

- Unified/checkor.py
Fixes checkor as the last PR #616 
ready
The PR #616 changes the size_worth_checking to a list of integers and the if condition changed in this PR was trying to give it a unicode. 
yes
#616 
n/a
@z4027163 @haozturk fyi
> size_worth_checking can't have unicode characters 

- Unified/actor.py
- Unified/showError.py
- utils.py
Add eos command for touch and tar.
For tar command, tar the file at /tmp and then use "eos cp" command to move to eos. Since "eos mv" command doesn't support overwrite option (-T). 
@sharad1126 @haozturk
> Change touch and tar command on eos to avoid IO issue

- Unified/showError.py
Machine 0272 is out of space due to large /tmp file, which is caused by the PR #630. 
Now remove those temporary files after they are copied into eos. 
@sharad1126 @haozturk
> rm the tem file after the eos cp

- Unified/assignor.py
For the output data placement noncustodial site selection, T1 only constraint is no longer needed. As discussed with L2, the site for output data placement is selected among T1+T2 sites based on their status and size. 
@sharad1126 @haozturk
> remove T1 only contraints for output placement.

- Unified/assignor.py
Fixes #637
not-tested
The issue was explained at #637 . In this PR, we disable hep cloud assignments for now due to the lack of hep cloud agents running them. After this PR is merged, we will kill&clone the stuck workflows.
YES
@sharad1126 @z4027163 @amaltaro @todor-ivanov FYI
> Disable hep cloud assignments

- utils.py
not tested
Do not convert to stepchain if there is a task whose eventStreams is nonzero
yes
@sharad1126 @z4027163
> Event Stream check for StepChain Conversion

- Unified/injector.py
add manual option to injector to bypass lock check.
> add manual to injector

- campaignAPI.py
Fixes https://github.com/dmwm/WMCore/issues/9756
not-tested
As we have recently learned, campaign configurations can have a specific parameter `toDDM` which can be used to make sure that a given datatier gets a nonCustodial output data placement, even if that same datatier is blacklisted in the Unified campaign.
That means, Unified needs to start publishing this parameter to the campaigns uploaded to central CouchDB. This schema change should parse the Unified campaign configuration and convert that value into `TiersToDM`, which will then get posted to central CouchDB campaign.
Once this PR gets merged, I'll update all the campaigns already available in central CouchDB.
No, in the sense that there is a campaign schema change in WMCore.
WMCore: https://github.com/dmwm/WMCore/pull/9906
none …
> Push one more campaign parameter - toDDM - to central Couch

- Unified/checkor.py
- Unified/closor.py
- Unified/equalizor.py
- Unified/injector.py
- Unified/subscribor.py
This change is for rucio testing WF. Ignore WFs that contain string 'rucio' in several modules unless those are run manully. 
Therefore we can create a separate branch where we can run those module manually on rucio testing WF.
> Skip string for rucio testing

- unifiedConfiguration.json
Since T2_EE_Estonia site is banned from production for 4 years, it's decided to remove this restriction and monitor the site's status in the upcoming days. The site performed well in the test workflow that we have assigned in the past weeks: 
https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=TEST-task_TOP-RunIISummer19UL17wmLHEGEN-00126
@z4027163 FYI
> Remove ban of T2_EE_Estonia from production jobs

- unifiedConfiguration.json
No issue created
ready
I just confirmed with the site admin (Valery) and he gave us the green light to make auto-approved transfer requests against their MSS endpoint.
yes
none
none
@haozturk feel free to merge it at any time, preferable before we enable MSOutput.
> Allow auto-approve for tape requests against JINR MSS storage

- acrontab.list
not-tested
This is the first step of disabling output data placement in Unified and enabling it WMCore:
1. stop unified moving workflows from "completed" to "closed-out".
2. run Unified closor module until all workflows in "closed-out" are moved to "announced" (here, Unified making the necessary placement)
3. CHECK: Unified must have moved all workflows from closed-out to announced
4. CHECK: MSOutput must have processed the same workflows in DRY-RUN (thus, no actual data placement. Workflows get marked as "done")
5. if the two checks above are satisfied, merge this Unified PR: https://github.com/CMSCompOps/WmAgentScripts/pull/653
6. re-enable all modules in Unified
7. fully enable MSOutput in production - thus, output data placement now go through MSOutput
YES 
@z4027163 FYI
> Temporarily stop completed to closed out transition

- unifiedConfiguration.json
No issue created
ready
It looks like Unified was relying on the unified parameter `tiers_keep_on_disk` to keep the LHE output datasets on disk (without any disk subscription?).
We overlooked that parameter when implementing MSOutput, so I suggest we actually allow this datatier to be subscribed to Disk. It will anyways be used as input dataset for other workflow(s). So we must have it on disk.
E.g. from MSOutput:
```
2020-09-24 08:49:17,143:WARNING:MSOutput: Output dataset configured to 0 copies, so skipping it. Details:
Workflow name: pdmvserv_task_HIG-RunIIFall17pLHE-00040__v1_T_200813_142709_4652
Dataset name: /SUSYGluGluToBBHToTauTau_M2900_TuneCP5_13TeV-powheg-pythia8/RunIIFall17pLHE-93X_mc2017_realistic_v3-v1/LHE
Campaign name: RunIIFall17pLHE
```
we will have to chase those …
> Allow LHE datatier to be subscribed to Disk

- acrontab.list
ready
This PR stops running subscribor module.
The subscription ability of the subscribor module has been removed with this PR #653 . The remaining code currently does nothing and since Unified does not do any output data placement anymore, this module could stop running.
yes
#653 
none
@z4027163  FYI
> Stop running subcribor module

- acrontab.list
Fixes #662 
ready
As discussed in the tagged issue, the responsibility of the stuckor module is out of the scope of Unified anymore. This PR stops running the stuckor module. In the upcoming weeks/months, we should evaluate the need of such monitoring from the perspective of workflow management. If needed, developing a new solution should be discussed.
yes
None
None
@z4027163 FYI
> Phedex2Rucio transition: Stop running stuckor module

- Unified/equalizor.py
- unifiedConfiguration.json
- utils.py
As discussed in the P&R meeting, we no longer require goodIO (T2 sites) for premix WFs, instead we choose all the T2 sites.
@haozturk @sharad1126
> change the siteWhiteList for premix WF

- Unified/checkor.py
- Unified/closor.py
- Unified/htmlor.py
- Unified/injector.py
- Unified/showError.py
Fixes #669 
not tested
1. Remove phedex dependant findLateFiles function which is redundant in the new implementatio
2. Remove findCustodialLocation function in checkor which is only used for phedex check
3. Remove findCustodialLocation function in htmlor which is only used for phedex check
4. disable dataset presence and block fraction info in the error reports
5. Remove getDatasetPresence function from checkor module
6. Remove getDatasetFiles function from injector
no
none
none
@z4027163  FYI
> Clear Redundant Phedex Dependencies

- Unified/assignor.py
Fixes #668 
ready
As discussed in #668, we will not close the dataset blocks in Unified. This is already supported by WMAgents. 
No (It relies on the current Rucio and WMAgents implementations)
None
@z4027163 @amaltaro @todor-ivanov FYI
> Phedex2Rucio transition: Do not close blocks in Unified

- acrontab.list
Fixes #675 
ready
As discussed in the Rucio transition meeting, we will stop running GQ module and use https://cmsweb.cern.ch/couchdb/workqueue/_design/WorkQueue/_rewrite/stuckElementsInfo to monitor stuck workflows. This link does not show all stuck workflows right now. 
@amaltaro  will fix it in the upcoming weeks.
yes
none
none
@z4027163  @amaltaro FYI
> Stop running GQ

- Unified/closor.py
- unifiedConfiguration.json
Fixes #670 
not tested
Instead of assigning DQM/DQMIO harvesting workflows to the sites where the input is, assign them to a predetermined set of sites to avoid querying data location. In the future, we can implement the first approach with the Rucio compatible functions.
no
none
none
@z4027163  @amaltaro  FYI
> Assign DQMHarvesting workflows to a pre-determined set of sites

- Unified/assignor.py
- utils.py
Fixes #683 
not tested
We do not need dynamo locking in assignor, since there is no DDM call in the module.
No
None
None
@z4027163
> Remove dynamo lock check from assignor

- campaigns.json
Updated neutrinoGun samples for the RunIISumer20UL16DigiPremix* campaigns from the 19 neutrino one to the 20 neutrino one. Also removed the top site list for one of the campaings.
> Adding neutrinoGun sample for 20UL16DigiPremix* campaigns

- acrontab.list
Fixes #690 
ready
Redundancy of the module is explained in the issue. This PR stops running the `inputs_summary` module. 
yes
None
None
@z4027163  FYI
> Stop running inputscycle

- unifiedConfiguration.json
ready
T2_BE_UCL and T2_CH_Beijing shows a good success with good pressure in running [our backfill test workflow](https://cmsweb.cern.ch/reqmgr2/fetch?rid=haozturk_TEST-BACKFILL-task_EGM-Run3Summer19wmLHEGS-00003__v1_T_201007_215727_4041) for goodAAA list:
```
T2_RU_IHEP: failure-exception:1, queued-retry:3211, success:60,
T2_CN_Beijing: transition:1, queued-retry:4, submitted-running:9, retry:588, pending:579, success:1897, cooloff-job:10,
T2_TR_METU: queued-retry:2404, submitted-retry:627, pending:627,
T2_RU_INR: queued-retry:143, submitted-retry:164, pending:164,
T2_BE_UCL: failure-exception:1, queued-retry:50, submitted-running:7, retry:1697, pending:1691, success:2240, cooloff-job:115
```
This PR adds these two sites to goodAAA list.
yes
Previous iteration: …
> Add UCL and Beijing to goodAAA

- Unified/assignor.py
- unifiedConfiguration.json
Tested locally, not tested in production
Include HEPCloud sites in the sitewhitelist of non-classical-mixing StepChain workflows in order to automate the assignments to these resources.
yes
none
none
@drkovalskyi @z4027163  FYI
> Include HEPCloud in the sitewhitelist of regular StepChain workflows

- Unified/checkor.py
Fixes #691 
not tested
Remove the `pick_SE` function call in checkor which relies on Phedex node names.
no
none
@z4027163  FYI
> Remove pick_SE function call in checkor

- Unified/assignor.py
- utils.py
Fixes #707 
tested locally, not in production
Earlier, we were including HEPCloud sites in the sitewhitelist of every StepChain request unless it reads classical mixing PU. With this PR, we include those sites to the sitewhitelist of workflows which read either PREMIX PU, primary input or no input. In other words, we do not include them in the whitelist of LHE workflows anymore, which are supposed to run at CERN.
yes
https://github.com/CMSCompOps/WmAgentScripts/pull/702
None
@z4027163  @drkovalskyi  FYI
> Fix the logic in HEPCloud assignments

- campaigns.json
Update secondary location of RunIISummer20UL18DIGIPremix as 
```
"T1_IT_CNAF",
"T1_US_FNAL",
"T2_CH_CERN"
```
> Update secondary of RunIISummer20UL18DIGIPremix

- utils.py
Fixes #709 
not tested
Unified checks if sites can satisfy the core and memory requirements of the requests during the assignment and eliminates the sites which cannot. It gets the site capacity information from `gwmsmon` which we cannot rely on anymore, since it is not supported as a service. This check was also blocking the HEPCloud assignments, since these sites were not included in the response coming from `gwmsmon`. This PR removes this check and leaves this matching to HTCondor. 
Practically speaking, looking at the logs of the past 30 days, only the following sites were eliminated from sitewhitelist during this check in addition of the HEPCloud sites:
```
[u'T2_BR_UERJ', u'T2_FI_HIP', u'T2_FR_GRIF_IRFU', u'T2_GR_Ioannina', u'T2_RU_INR', u'T2_TR_METU']
```
yes
#702 #708 
none …
> Remove core and memory capacity check during assignment

- utils.py
Fixes #713
not tested
This check is practically redundant for now as there is no site restricted because of it. Only HEPCloud sites are restricted due to a problem in information source. This PR removes this check temporarily
yes
#702 #708 #712 
none
@z4027163  FYI
> Remove CC7 check temporarily

- campaigns.json
Adding in RunIISumer19UL*NanoAOD%v2 and RunIISumer20UL*NanoAOD%v2
*=16,17,18
% is either nothing or APV for when*=16
Added in RunIISummer20UL16wmLHENanoGEN
Also removed CERN from the secondary location for these PU datasets:
/Neutrino_E-10_gun/RunIISummer17PrePremix-PUAutumn18_102X_upgrade2018_realistic_v15-v1/GEN-SIM-DIGI-RAW
/Neutrino_E-10_gun/RunIISummer17PrePremix-MCv2_correctPU_94X_mc2017_realistic_v9-v1/GEN-SIM-DIGI-RAW
/Neutrino_E-10_gun/RunIISpring15PrePremix-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v2-v2/GEN-SIM-DIGI-RAW
/Neutrino_E-10_gun/RunIISummer19ULPrePremix-UL17_106X_mc2017_realistic_v6-v1/PREMIX
/Neutrino_E-10_gun/RunIISummer19ULPrePremix-UL16_106X_mcRun2_asymptotic_v10-v2/PREMIX
FNAL is the only site for these secondaries
> Fixing mistakes from the commit for the NanoAODv2 UL

- Unified/showError.py
- unifiedConfiguration.json
Fixes #720
not tested
As the ACDC console address changes, we need to make unified compatible with the new console. For now, only necessary change that I can think of for Unified is to update the hyperlink to the Console in the error report and this PR does that.
no
none
none
@z4027163  FYI
> Make acdc console address configurable

- Unified/showError.py
Fixes #720
not tested
We were giving parameters in the wrong order. This PR fixed it.
yes
#721 
none
none
> Bug fix in href to ACDC console

- campaigns.json
The NanoAODUL18Data and NanoAODUL17Data campaigns are true now the pilots seemed to be successful.
> NanoAOD20 Data campaigns pilots successful campaigns open

- campaigns.json
https://its.cern.ch/jira/projects/PRCAMPAIGNS/issues/PRCAMPAIGNS-161?filter=allopenissues&orderby=updated+DESC%2C+priority+DESC
https://its.cern.ch/jira/projects/PRCAMPAIGNS/issues/PRCAMPAIGNS-165?filter=allopenissues&orderby=updated+DESC%2C+priority+DESC
https://its.cern.ch/jira/projects/PRCAMPAIGNS/issues/PRCAMPAIGNS-167?filter=allopenissues&orderby=updated+DESC%2C+priority+DESC
https://its.cern.ch/jira/projects/PRCAMPAIGNS/issues/PRCAMPAIGNS-157?filter=allopenissues&orderby=updated+DESC%2C+priority+DESC
https://its.cern.ch/jira/projects/PRCAMPAIGNS/issues/PRCAMPAIGNS-155?filter=allopenissues&orderby=updated+DESC%2C+priority+DESC
All the nanoAOD campaigns that were requested to be open are open but the NanoAOD20UL17 because of an issue that seems to be related to the release that pdmv …
> Updating for pilots that were successful

- campaigns.json
Fixes #735 
ready
Set the fractionpass of NanoAODUL1*Data campaigns to 1 since these are data campaings, not MC.
yes
none
none
@scarletnorberg  @z4027163  FYI
> Set the fractionpass of NanoAODUL1*Data campaigns to 1

- unifiedConfiguration.json
Partially fixes #725 
ready
Add T2_UA_KIPT, T2_AT_Vienna, T2_ES_IFCA to goodAAA list. Justification can be found at the related issue.
yes
#642  and #699 
none
@z4027163  FYI
> Add T2_UA_KIPT, T2_AT_Vienna, T2_ES_IFCA to goodAAA list

- campaigns.json
dealing with PRCAMPAIGNS-168 to PRCAMPAIGNS-178 where RunIISummer20UL*MiniAOD*v2 and the MiniAODUL*Data campaigns 
As well as PRCAMPAIGNS-158 PRCAMPAIGNS-165 which was removing the fractionpass all nanoAOD campaigns have fractionpass removed we will see how this goes.
> Adding in new MiniAOD campaigns

- unifiedConfiguration.json
- utils.py
tested
It is seen that some T3 sites are not used in production very well. After running a test workflow in these sites, here is what we get:
```
T3_US_Rutgers: submitted-retry:57, pending:150, first:93,
T3_US_Baylor: success:1321, submitted-running:11, retry:54, pending:150, first:107,
T3_US_Colorado: success:5921, submitted-running:36, retry:290, pending:714, first:460, failure-exception:4, queued-retry:49, cooloff-job:102,
T3_UK_London_RHUL: success:1021, submitted-retry:146, pending:238, first:94, running:2, queued-retry:103, cooloff-job:88,
T3_UK_SGrid_Oxford: success:940, submitted-running:9, retry:861, pending:954, first:102, queued-retry:30, cooloff-job:89,
T3_US_OSG: submitted-retry:31, pending:280, first:249, 
```
This was the sitewhitelist:
```
"SiteWhitelist": [
"T3_FR_IPNL", …
```
> Add some T3 sites to goodAAA list

- campaigns.json
Removing "secondary_AAA": false, RunIISummer20UL16wmLHEGENAPV because there is no secondary_AAA
> Removing the secondary addition

- Unified/closor.py
Fixes #729 
not tested
The necessity of spawning harvesting workflows is under discussion and it is expected to be resolved in the next PdmV-PnR meeting at `11.01.2021`. This PR stops spawning harvesting workflows temporarily. Upcoming development should be done after the meeting once the requirements are in place.
yes
None
None
@z4027163  FYI
> Stop spawning harvesting workflows

- campaigns.json
Since, these are LHE workflows and they are assigned to CERN. If CERN is not defined as a secondary location in the campaign, MSTransferor does not take them into account.
> Add CERN as a secondary location for RunIISummer19UL16DIGIPremixAPV

- unifiedConfiguration.json
Fixes #739 
ready
This PR adds the following sites to the goodIO list according to the 1st iteration of the test.
```
"T2_KR_KISTI","T2_UK_SGrid_RALPP","T2_BR_SPRACE","T2_UA_KIPT"
```
Detailed result and analysis of the test can be found at this issue.
yes
None
None
@z4027163  FYI
> Add 4 new sites to the goodIO list

- utils.py
Fixes #753
not tested
This PR intends to solve the following error:
```
cmsunified
vocms0269.cern.ch
module batchor
SI = global_SI()
File "/data/unified/WmAgentScripts/Unified/utils.py", line 2705, in global_SI
global_SI.instance = siteInfo(a)
File "/data/unified/WmAgentScripts/Unified/utils.py", line 2270, in __init__
self.fetch_detox_info(talk=False, buffer_level=UC.get('DDM_buffer_level'), sites_space_override=sites_space_override)
File "/data/unified/WmAgentScripts/Unified/utils.py", line 2437, in fetch_detox_info
queued = self.queue.get(site,0)
AttributeError: 'str' object has no attribute 'get'
Abnormal termination with exit code 1
```
no
#754 
none
None
> Comment out the redundant line which gives errors

- Unified/assignor.py
Fixes #761 
tested locally
This PR excludes CERN HLT from the sitewhitelist of workflows whose AAA is enabled. Details are at #761 
yes
None
None
@z4027163  FYI
> Do not include CERN HLT in the sitewhitelist of workflows whose AAA is enabled

- Unified/equalizor.py
Fixes #767 
not tested
This PR disables sitewhitelist extension with HLT due to the reason reported in the issue. For more details please see [1]
[1] https://its.cern.ch/jira/browse/CMSCOMPPR-18198
yes
None
None
@z4027163  FYI
> Disable sitewhitelist extension with HLT

- campaigns.json
Fixes #769 
not tested
Details: https://its.cern.ch/jira/browse/CMSCOMPPR-18198 & #769 
This PR blacklists `T2_CH_CERN` for the following campaigns:
```
RunIISummer16DR80Premix
RunIISummer19UL18DIGIPremix
RunIIFall17DRPremix
RunIIAutumn18DRPremix
RunIIFall18GS
RunIIFall17wmLHEGS
RunIIFall18wmLHEGS
RunIIFall17DRPremix
RunIISummer15wmLHEGS
RunIIFall17GS
RunIISummer15GS
RunIISummer19UL18DIGIPremix
RunIISummer19UL18GEN
RunIISummer19UL18wmLHEGEN
```
Note that these campaigns related to chains where a PREMIX pileup it needed and those PREMIX pileups are not present at `T2_CH_CERN`
<YES | NO>
-
-
@scarletnorberg @z4027163  FYI
> Blacklist T2_CH_CERN from various campaigns

- campaigns.json
Fixes #788 
not tested
This PR converts all PSN names into RSE names in the campaign configuration for the secondary locations.
no
none
none
@amaltaro  @scarletnorberg  @jenimal  @z4027163  FYI
> Convert all PSN names into RSE names in the campaign configuration for the secondary locations

- assistance/Workflow.py
- assistance/utils/SearchTools.py
- assistance/utils/UnifiedConfiguration.py
- assistance/utils/WebTools.py
Fixes #794 and #786 
tested locally
```
workflow = Workflow('asikdar_RVCMSSW_11_3_0_pre2BuMixing_14_PU__rsb_210203_115825_5941')
print workflow.getPrepID()
print workflow.getNumberOfEvents()
print workflow.getRequestType()
print workflow.getSiteWhitelist()
print workflow.getCampaigns()
print workflow.getPrimaryDataset()
print workflow.getSecondaryDatasets()
```
Output:
```
CMSSW_11_3_0_pre2__fullsim_PU_2021_14TeV-1612349769-BuMixing_14
11746
TaskChain
[u'T1_US_FNAL']
[u'CMSSW_11_3_0_pre2__fullsim_PU_2021_14TeV-1612349769']
[u'/RelValBuMixing_14/CMSSW_11_3_0_pre2-113X_mcRun3_2021_realistic_v2_rsb-v1/GEN-SIM']
[u'/RelValMinBias_14TeV/CMSSW_11_3_0_pre2-113X_mcRun3_2021_realistic_v2_rsb-v1/GEN-SIM']
```
This PR includes getter functions for workflow parameters.
Yes
#771
Yes:
``` …
```
> Main functionality to get workflow parameters

- campaignAPI.py
Fixes #800
not tested
This PR removes the following functionality in pushing the campaigns to WMCore/CouchDB: Do not push inner level SiteWhitelist as a top level Sitewhitelist in the campaigns
no
None
Does not introduce a new external dependency.
@amaltaro  @z4027163  FYI
> Do not push inner level SiteWhitelist as a top level Sitewhitelist in the campaigns

- RucioClient.py
- utils.py
Fixes #796 
tested locally on branch 796-fix:
```
>>> from utils import workflowInfo
>>> workflow = workflowInfo('cmsweb.cern.ch','cmsunified_task_JME-RunIISummer20UL16DIGI-00004__v1_T_210116_092125_3670')
>>> (lheinput,primary,parent,secondary, sites_allowed, sites_not_allowed) = workflow.getSiteWhiteList()
...
Reading minbias
Initially allow [u'T1_IT_CNAF', u'T2_US_Nebraska']
After all of these, allowing: [u'T1_IT_CNAF', u'T2_US_Nebraska']
After all of these, not allowing: []
>>> sites_allowed
[u'T1_IT_CNAF', u'T2_US_Nebraska']
```
which is correct:
```
[haozturk@lxplus798 ~]$ rucio list-rules cms:/MinBias_TuneCP5_13TeV-pythia8/RunIISummer20UL16SIM-106X_mcRun2_asymptotic_v13-v2/GEN-SIM
ID                                ACCOUNT            SCOPE:NAME …
```
> Restrict the sitewhitelist to the sites hosting the PU for workflows with classical mixing PU 

- campaigns.json
Disable: 
```
Phase2Spring21DRMiniAOD
Phase2D81Spring21GS
Phase2D80Spring21GS
Phase2D76Spring21GS
```
Since pilots are not finished, yet. 
Fix secondary for: `Run3Winter20DRMiniAOD`
```
$ rucio list-rules cms:/MinBias_TuneCP5_14TeV-pythia8/Run3Winter20GS-110X_mcRun3_2021_realistic_v6-v1/GEN-SIM
/cvmfs/cms.cern.ch/rucio/x86_64/slc7/py2/current/lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py:47: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
from cryptography import x509
ID                                ACCOUNT            SCOPE:NAME                                                                                  STATE[OK/REPL/STUCK]    RSE_EXPRESSION …
```
> Disable some campaings and fix one secondary

- campaigns.json
PRCAMPAIGNS-201 pilot successful
PRCAMPAIGNS-202 pilot successful
PRCAMPAIGNS-203 pilot successful
Yes pilot was successful 2.1 days ago
PRCAMPAIGNS-191 open pilot successful This one finished this morning and showed 
Number of events requested | 20,000
-- | --
Number of events produced | 19,764 (98.8%)
But is I checked:
/DYJetsToLL_TuneCUETP8M1_5020GeV-amcatnloFXFX-pythia8/HINPbPbWinter16wmLHEGSHIMix-75X_mcRun2_HeavyIon_v14-v1/GEN-SIM 21/21 = 100.00%
/DYJetsToLL_TuneCUETP8M1_5020GeV-amcatnloFXFX-pythia8/HINPbPbWinter16wmLHEGSHIMix-75X_mcRun2_HeavyIon_v14-v1/LHE 21/21 = 100.00%
It seems to think it is 100% of the lumi blocks are done. There was an issue that talks about this so I think it is done and left it as go is true.
https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id= …
> Redoing the turning of campaigns

- campaigns.json
Fixes secondary for pPb816Spring16GS. We should include CERN because of the pLHE requests. Secondary is about 5TB, so, space is not an issue.
> Fix secondary for pPb816Spring16GS

- campaigns.json
Set Fractionpass to 95% for NanoAODv9 campaigns. 
@scarletnorberg  fyi
> Set Fractionpass to 95% for NanoAODv9 campaigns

- resubmit.py
Fixes #847
tested w/ a stepchain: https://cmsweb.cern.ch/reqmgr2/fetch?rid=haozturk_task_BPH-RunIISummer20UL16GENAPV-00054__v1_T_210612_132502_1869
not tested w/ a taskchain yet
With this PR, we can alter filter efficiency of a given task or step of a workflow. Example usage: 
```
python resubmit.py -a clone -b --filterEff 0.0002 --taskNumber 1 cmsunified_task_BPH-RunIISummer20UL16GENAPV-00054__v1_T_210506_102253_8154
```
None
No additional dependency
@z4027163  FYI
> Alter filter efficiency in resubmit.py

- reqMgrClient.py
- setCascadeStatus.py
- setReqMgrStatus.py
Fixes #864 
tested w/ https://its.cern.ch/jira/browse/CMSCOMPPR-19530 
Currently we only support "to staged", "to closed-out" and "to announced" transitions. The script can be improved, but it works for now. 
Example use:
```
python setReqMgrStatus.py -f ~/workflowsToStaged.txt -s staged
```
yes
None
ReqMgr
@z4027163
> Set workflows to staged status manually

- unifiedConfiguration.json
- utils.py
Fixes #872
tested:
High priority workflow: 
```
$ python Unified/step_chain_test.py pdmvserv_task_EXO-RunIISummer15wmLHEGS-12830__v1_T_210705_212330_4936
{u'Task1': {'cores': 1, 'tpe': 15.995700000000001}, u'Task2': {'cores': 8, 'tpe': 17}, u'Task3': {'cores': 8, 'tpe': 17}, u'Task4': {'cores': 8, 'tpe': 0.1985}}
Total time per event for TaskChain: 50.2
CPU efficiency of StepChain with 4 cores: 76.1%
High priority workflow pdmvserv_task_EXO-RunIISummer15wmLHEGS-12830__v1_T_210705_212330_4936 is okay to be converted to stepchain with efficiency 0.760992803949
pdmvserv_task_EXO-RunIISummer15wmLHEGS-12830__v1_T_210705_212330_4936: True
```
Low priority workflow:
```
$ python Unified/step_chain_test.py pdmvserv_task_B2G-RunIISummer15wmLHEGS-05564__v1_T_210703_205629_7185
{u'Task1': {'cores': …
```
> Lower stepchain conversion threshold for high priority workflows

- Unified/checkor.py
Not fixes but circumvents #886
not tested
Prioritization in checkor is not critical. Maximum number of workflows processed in a round is 500 and we have 1.2k workflows in `completed` right now, which is the highest number for months. Checkor's duty cycle is couple of hours in general, so it shouldn't delay the high prio stuff w/ this PR. This quick workaround is needed to digest the workflows in the system quickly and open-up some space in the unmerged space, which is quite critical right now.
yes
None
None
@z4027163  FYI
> Temporarily disable prioritization in checkor to circumvent issue 886

- Unified/actor.py
Fixes #891 
not tested
With this PR, we set the memory within tasks for the ACDC of taskchains. Global memory setting gives issues.
Will monitor the stuck ACDCs which are https://wfrecovery.cern.ch/getaction?days=15 
None
No new dependency
@z4027163  FYI
> Set memory within tasks (not global) for the ACDC of taskchains

- campaigns.json
Pilot successful PRCAMPAIGNS-217 although it did go through the ringer
pPb816Spring16GS for this campaign /ReggeGribovPartonMC_EposLHC_pPb_4080_4080/pPb816Spring16GS-80X_mcRun2_asymptotic_v17-v1/GEN-SIM removing CERN 
there are 12 WF's all not currently running so now is a good time to switch. Two sites still in use.
> Pilot successful and removing a pileup file from CERN

- Unified/actor.py
Fixes #891 
not tested
#894 was not enough. We need to also set global memory parameter. https://github.com/CMSCompOps/WmAgentScripts/issues/891#issuecomment-893297027 
#894 
No
@z4027163
> Set global memory parameter, too for custom memory ACDCs

- Unified/assignor.py
A workaround for #868 
not tested
Temporarily switch off priorization in assignor. See the issue for reason.
#869 
None
None
> Temporarily switch off priorization in assignor

- Unified/htmlor.py
A workaround for #868 
not tested
Temporarily disable caching in htmlor to get workflows in assignment-approved
#912 
None
None
> Temporarily disable caching in htmlor to get workflows in assignment-approved

- Unified/jiraHandler.py
- jiraCycle.sh
Fixes #967 
tested locally, works fine: ready
If the workflow status isn't one of the following states, JIRA closes automatically:
```
['assignment-approved', 'running-open','running-closed','completed','acquired', 'staging', 'staged', 'assigned', 'closed-out', 'failed']
```
None
JIRA
@jenimal @z4027163
> Close unnecessary JIRA tickets automatically

- campaigns.json
Ran the json checker jq.
PRCAMPAIGNS-250
PRCAMPAIGNS-251
PRCAMPAIGNS-252
PRCAMPAIGNS-253
Seem to be heavy ion campaigns and similar to another and seem to be implied that they are double checking the site black list with jordan.
> New PP5TeV new heavy ion campaigns

- archive_campaigns.json
- campaigns.json
PRCAMPAIGNS-35 adding pileup to pPb816Spring16GS will check WF's
PRCAMPAIGNS-254 RunIISpring16FSSIMDRPremix This is the one I checked with Jordan should be good to go.
PRCAMPAIGNS-251 RunIISummer20UL17pp5TeVDIGI pilot successful 
PRCAMPAIGNS-252 RunIISummer20UL17pp5TeVHLT pilot successful 
PRCAMPAIGNS-253 RunIISummer20UL17pp5TeVRECO pilot successful
PRCAMPAIGNS-243 RunIISpring21UL16FSSIMDR pilot successful although still dealing with pileup placement which is weird but we will talk to data management about it
PRCAMPAIGNS-244 RunIISpring21UL16FSSIMDRPremix pilot successful although still dealing with pileup placement which is weird but we will talk to data management about it
> Updates on JIRA tickets etc so a massive update

- campaigns.json
Changing RunIISummer19UL16DIGI because T1_US_FNAL instead of T1_US_FNAL_DISK
[PRCAMPAIGNS-258](https://its.cern.ch/jira/browse/PRCAMPAIGNS-258)
[PRCAMPAIGNS-280](https://its.cern.ch/jira/browse/PRCAMPAIGNS-280) go is true pilot successful
Run3Winter22PbPbGS campaign adding minbais
[PRCAMPAIGNS-275](https://its.cern.ch/jira/browse/PRCAMPAIGNS-275) adding minbias
> Adding new pile and removing wrong RSE

- campaigns.json
These are a go: [PRCAMPAIGNS-278](https://its.cern.ch/jira/browse/PRCAMPAIGNS-278), [PRCAMPAIGNS-276](https://its.cern.ch/jira/browse/PRCAMPAIGNS-276), [PRCAMPAIGNS-259](https://its.cern.ch/jira/browse/PRCAMPAIGNS-259), [PRCAMPAIGNS-260](https://its.cern.ch/jira/browse/PRCAMPAIGNS-260), [PRCAMPAIGNS-261](https://its.cern.ch/jira/browse/PRCAMPAIGNS-261), [PRCAMPAIGNS-258](https://its.cern.ch/jira/browse/PRCAMPAIGNS-258), [PRCAMPAIGNS-257](https://its.cern.ch/jira/browse/PRCAMPAIGNS-257)
The pilots were successful.
> Adding some campaigns to go

- campaigns.json
The new FS and the Run3 campaign had no secondaryAAA true so adding that for 4 campaigns
> Adding secondary_AAA: true for 4 campaigns

- Unified/batchor.py
- batchor_cycle.sh
Fixes #1090 
ready
[Py2Py3] Migrate module Unified/batchor
> [Py2Py3] Migrate module Unified/batchor

- Unified/checkor.py
- Unified/createLogDB.py
- Unified/showError.py
- Unified/whatLog.py
- cWrap.sh
- showError_cycle.sh
- unifiedConfiguration.json
Fixes #1095 
In development
Migrate module Unified/checkor (fast)
> WIP: Migrate module Unified/checkor (fast)

- campaigns.json
@haozturk Per requests from:
- https://its.cern.ch/jira/browse/PRCAMPAIGNS-341
- https://its.cern.ch/jira/browse/PRCAMPAIGNS-340
- https://its.cern.ch/jira/browse/PRCAMPAIGNS-329
And also from what we discussed with sysadmins from HLT and MIT.
> enabling campaigns + removing HLT and MIT from el8 blacklist

- .gitignore
- es_opensearch.py
<ready>
implements OpenSearch interface to communicate with new es-unified1.cern.ch
<YES> es_opensearch client can be used separately from curl to es-unified7 requests.
New module is required: `opensearch-py~=2.1`
@haozturk
> Implement es_opensearch.py

- es_opensearch.py
<ready>
Daily indices size of unified-logs is very small and it is switched to MONTHLY indices to correspond with ES/OpenSearch index management best practices. They will have 1 replica and 1 shard which is enough.
<NO> Daily indices should be deleted in test OpenSearch cluster. No effect to production.
> Change daily OpenSearch index to monthly index

- campaigns.json
Adding the following params within `secondaries` key:
- `keepOnDisk`: corresponds to `active` in MSPileup
- `fractionOnDisk`: specifies what fraction of pileup to keep on disk. It's 1.0 for all campaigns currently
Also removing empty `secondaries` keys
> Add keepOnDisk and fractionOnDisk params to campaigns

- autoACDC/runner.py
Follow up to previous PR, adds a minor fix, namely a renaming: workflows to be skipped are now named 'problematic', and I've added a flag --doProblematic to runner.py, which can be used to turn on/off the skipping of problematic workflows from the autoACDC, giving the user more control.
> added flag for probelematic wfs

- Unified/closor.py
Closor seems to be failing on the JIRA actions it takes.
While I don't understand why it hangs for so long, as a first attempt to solving this, we can try to remove the JIRA logic from the script.
The already-running Unified/jiraHandler.py is already closing out tickets with status = 'announced'.
> removing JIRA logic from closor.py

- autoACDC/autoACDC.py
Modified the autoACDC class so that ReReco tasks that are DataProcessingMergeDQMoutputEndOfRunDQMHarvestMerged raise an Exception, since they will get stuck on the server side.
> Skip DataProcessingMergeDQMoutputEndOfRunDQMHarvestMerged tasks in ReReco

- Unified/checkor.py
checkor was stopping at the first comment that matched a pattern. change this to allow multiple comments to be checked. avoids cases when an user who isn't authorized to bypass tries to, and blocks the checking of any further comment.
> let checkor look at all comments

- campaigns.json
@z4027163 @tyjyang 
Add a secondary for RunIIAutumn18DR which is included in these requests [1] [2]
This commit restores some of PU from original requests [3]
SiteWhitelist is changed to T2_US_Caltech according to [4]
[1] https://[dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_BPH-RunIIFall18GS-00446](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_BPH-RunIIFall18GS-00446)
[2]  https://[dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_BPH-RunIIFall18GS-00447](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_BPH-RunIIFall18GS-00447)
[3] https://its.cern.ch/jira/browse/CMSCOMPPR-5516
[4] https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=site+dataset%3D+%2FMinBias_TuneCP5_13TeV-pyth …
> Add a secondary for RunIIAutumn18DR

- campaigns.json
@z4027163 @tyjyang 
1. Enable RunIISummer20UL16wmLHENanoGENpruned as its pilot is successful [1]
2. Add a secondary for HINPbPbAutumn18GS [2], RunIIAutumn18DR [3][4], RunIISpring21UL[16|17]FSwmLHEGSDR [5][6]
3. Remove a specific site from their siteblacklist as the site is identical to the PU location
- PU location of RunIIAutumn18DR : T2_US_Caltech <-- blacklisted in RunIIFall18GS [7]
- PU location of RunIISpring21UL[16|17]FSwmLHEGSDR : T2_CH_CERN <-- blacklisted in their campaign [8]
[1] https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_PPD-RunIISummer20UL16wmLHENanoGENpruned-00001
[2] https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIN-HINPbPbAutumn18GSHIMix-00225
[3] https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_BP …
> Enable RunIISummer20UL16wmLHENanoGENpruned and add secondaries for HINPbPbAutumn18GS, RunIIAutumn18DR, RunIISpring21UL[16|17]FSwmLHEGSDR

- unifiedConfiguration.json
removed T2_UA_KIPT (Ukrainian site) from banned sites list.
@haozturk
> remove T2_UA_KIPT from banned sites list

- src/python/Services/McM/McMClient.py
Invalidator was crashing after SSO change by @haozturk due to redirects. 
Added config in mcm client to handle redirects. 
checked on vocms0277, Invalidator is working.
> Update McMClient to support 301 redirects. 

- McMClient.py
actor was crashing after SSO change by @haozturk due to redirects.
Added config in mcm client to handle redirects.
checked on vocms0277, actor is working.
> Update McMClient to support 301 redirects in branch , migration-fast
