RelVal/change_old_wf_status.py, closeOutWorkflows_leg.py, issues/getoverview.py, listWorkflows.py, production_taskchain_workflows.py
This is not complete patch, need to change the keyword for the return value.
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/WMStats/WMStatsReader.py#L5
following function could be used but preferably just change the underlining key word.
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/WMStats/WMStatsReader.py#L33
=> initial attempt to adapt view change

resubmit.py
For the https://github.com/dmwm/WMCore/pull/5496
=> fix for LumiList

CondorMonitoring/JobCounter.py
- Replaces all the queries to condor_q and condor_status for the equivalente python condor client way
- Job type is taken from the classAds (CMS_JobType). Logic to decude job type is only a backup now, in case the first is not available.
- Minor changes to add simplicity
- Performance improvement (2 times faster)
- Solves the problem of too many emails :-)
=> Use HTCondor python for Condor Monitoring

StoreResults/MigrationToGlobal.py, StoreResults/RequestQuery.py, StoreResults/createStoreResults.py, assignProdTaskChain.py, issues/plotAgeDistribution.py
=> Include StoreResults scripts

recover/recover-v2.py
In the end it was only 2 lines of change. We're still running a recovery workflow, so don't merge until we get positive results.
Besides that, there are 2 things to be fixed here:
1. handle ReReco with IncludeParents flag on
2. handle ReReco with lumiList
For more info, see
https://cms-logbook.cern.ch/elog/Workflow+processing/22154
=> Make recovery script work with DBS3 (and PNN stuff)

reqMgrClient.py
Still need to add put request and assign etc. This is NOT tested. @julianbadillo, Julian, could you review?
=> initial patch to use reqmgr2 api

Unified/addHoc.py, Unified/assignor.py, Unified/checkor.py, Unified/closor.py, Unified/completor.py, Unified/equalizor.py, Unified/go_condor.py, Unified/invalidator.py, Unified/recoveror.py, Unified/rejector.py, Unified/stagor.py, Unified/transferor.py, cWrap.sh, campaigns.json, reqMgrClient.py, unifiedConfiguration.json, utils.py
preparing for a merge with testbed and rewmgr2 changes.
=> Latest developments

Unified/equalizor.py, Unified/go_condor.py, Unified/my_condor.py
@bbockelm please take a look.
@juztas for the source of these values
not to be merged
=> set memory and time from experience

reqMgrClient.py
Replaces #147
@prozober @areinsvo @vlimant please review and test
=> Take2: Properly handle reqmgr one response for request creation

reject.py, resubmit.py
Memory is set as a float in resubmit.py and reject.py
=> Memory is set as a float

makeACDC.py, makeAllACDCs.py
Memory to override the original request memory on ACDCs.
=> Memory to override the original request memory on ACDCs

resubmit.py
@AndrewLevin is having problems with clones into reqmgr2.
We have much more information in the workload of reqmgr2 requests, and this script was creating "new" workflows with some keys/values that are not meant to be provided by the user.
Andrew, @prozober please test it
@ticoann @vlimant please review
=> Cleanup of key/values for cloning workflows into reqmgr2

recover/recoverMissingLumis.py
@prozober @jenimal can you test this fix please?
=> Set PrepID and Campaign for recovery workflows

recover/recoverMissingLumis.py
up for scrutiny @amaltaro @ticoann @prozober
=> a fix to make things faster and actually get the parent information

resubmit.py
fixes https://github.com/dmwm/WMCore/pull/5489 (partially). 
Additional patch is created https://github.com/dmwm/WMCore/pull/7103
=> Add Total stats for resubmit filter list

assign.py, reqMgrClient.py
@prozober as discussed, this pulls in the sites from the acdc doc.
@amaltaro @ticoann applies the memory in assignment is needed.
checks the sites memory/core requirements for overlap with the site whitelist.
to be tested. @prozober just shoot me a chat when there is an acdc to be assigned so that I can try it out.
=> Assign from acdc

recoverMissingLumis.py
Related to #193.
I did a couple of tests, and everything is working OK.
Could someone please merge the changes?
=> recoverMissingLumis using rqMgr2 API

assign.py, recoverMissingLumis.py
Two changes:
1. recoverMissinLumis.py: A change in the nodes' name for the blockLocations. 
2. assign.py: If xrootd and secondary xrootd variables are not given, we are going to assign "False" by default, or the values from the original request (if not null).
=> recoverMissingLumis and assign changes

recoverMissingLumis.py
@prozober please review and test. First commit has important changes, 2nd one is only aesthetic and convention fixes.
=> Replace SE by PNN in the recovery script

Unified/assignor.py, Unified/cachor.py, Unified/go_condor.py, campaigns.json, campaigns.relval.json
@bbockelm does this look OK ? any suggestion ?
=> Hook hold release

Unified/go_condor.py, Unified/job_router_modules/unified_utils.py
this should solve the overflow rules going to extra sites
=> modified rules to not add things from extdesiredsites

condor_overview.py
A few minor fixes to the condor_overview script, which maybe nobody else uses anymore...
=> Condor overview: properly fetch the running site, job type, running time and harvesting jobs

component_down.py, wmagent_status.py
Attempting to do a pr for the plotting script and the tracking json file.
=> Agent plotting

injectHarvest.py
Has a few aesthetic last minute changes, so you might want to test it before merging (only functionality, logic should be Ok).
There is a need to rerun harvesting on from this workflow:
zhenhu_RVCMSSW_9_2_8VBFHToBB_M125_Pow_py8_Evt_13UP17__HS_170809_220847_85
see workflow team thread with subject "9_2_9_vs_9_2_8 relmon stuck?"
=> Script to create a harvesting-only workflow from any other wf

unifiedConfiguration.json
https://ggus.eu/index.php?mode=ticket_info&ticket_id=134978
=>  Add T1_IT_CNAF_MSS to list of sites autoapproving tape transfer request

Unified/htmlor.py, resubmit.py
@prozober to solve the issue with manual cloning. To be tested
=> manual clone

Unified/actor.py, Unified/rejector.py, reqMgrClient.py, resubmit.py
@prozober to be tried to fix what you've seen in testing #282 
@areinsvo @SvenjaPflitsch there is some level of testing that needs to be done in actor.
rejector.py should be untouched since I used its code centrally.
=> Fix all cloning

utils.py
@thongonary you'll have to check whether it fits #277 
@SvenjaPflitsch N.B.  GB_space_limit unified configuration will have to be edited down to 20
=> Restrict output size to a single size

Unified/actor.py
=> swift re-entry of clones

utils.py
@thongonary @mcremone @SvenjaPflitsch go ahead when you are ready https://its.cern.ch/jira/browse/CMSCOMPPR-3480
=> parentage issue on stepchain fixed

Unified/checkor.py
is this going to help on https://github.com/CMSCompOps/WmAgentScripts/issues/309
=> threaded checkor

Unified/injector.py
If there is no obvious reason not to merge, I will merge this by 5 PM today.
=> no conversion for relval

postcycle-review-manual.sh, postcycle-review-recovering.sh, postcycle-strict.sh, postcycle-update.sh, unifiedConfiguration.json
as these are running from separate sub list of workflows, there should be no interference
=> split the cycles

Unified/go_condor.py
that should free the queue of things already submitted
=> routing rule for PhaseIISummer17wmLHEGENOnly

Unified/checkor.py
related to https://github.com/dmwm/WMCore/issues/8148 and the issue with not knowing when to deal with a file mismatch, there's a 2 days grace period added in unified before labelling "filemismatch". It will label "agentfilemistmatch" in the meantime
=> mitigate file injection delay from the agent

Unified/htmlor.py, utils.py
removing a couple of files on eos, in favor or direct access in oracle of mongodb
=> people should read status from DBs

Unified/assignSchema.py, Unified/assignSession.py, utils.py
remove any usage of files for locking items and runtime lock
=> communication on locks

Unified/addHoc.py, Unified/batchor.py, Unified/closor.py, Unified/htmlor.py, Unified/rejector.py, campaigns.json, campaignsConfiguration.py, utils.py
vlimant@vocms0275.cern.ch >python campaignsConfiguration.py --help
Usage: campaignsConfiguration.py [options]
Options:
-h, --help            show this help message and exit
--dump=DUMP           dump the whole content in this file
--load=LOAD           synchronize the db with the content of this file
-n NAME, --name=NAME  a campaign name to be viewed/added/updated
--remove              remove the specified campaign
-c CONFIGURATION, --configuration=CONFIGURATION
a json doc for the campaign to be add/updated
-p PARAMETER, --parameter=PARAMETER
a single parameter to be updated of the form key:value
or a.b.key:value for nested
can be used to update the campaign configuration, from a full json, or a single json for a new campaign, or updating one parameter only
=> Campaign batch mongodb

utils.py
@sharad1126  et al, looks like it impacted https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_EXO-RunIIFall17pLHE-00172
=> fix on events per lumi

Unified/equalizor.py, utils.py
would require some load in the system to try explicitely on a workflow pending in the UK
=> adding T3_UK_Opportunistic_dodas

Unified/equalizor.py, utils.py
Reverts CMSCompOps/WmAgentScripts#331
=> Revert "adding T3_UK_Opportunistic_dodas"

Unified/go_condor.py
@drkovalskyi  once the require Charmonium blocks are at CERN, this can be merged.
that serves as a recent example to add an adhoc jobrouting rule via unified @sharad1126
=> charmonium rereco at cern

Unified/go_condor.py
@thongonary can you have a look. I have added MuonEG to the file to make it run at CERN.
@vlimant FYI
=> adding muoneg to send it to T2_CH_CERN

Unified/showError.py, utils.py
we've observed modules hanging because of checking on components. this puts a default 2 min timeout on that check and returns the value of the check otherwise
=> Checking on components with a timeout

utils.py
to overcome https://github.com/SmartDataProjects/dynamo/issues/253
=> caching api for dynamo

Unified/closor.py, utils.py
=> Threaded closor

Unified/showError.py, utils.py
@sharad1126 take a look. sounds sane to me so far
=> Trying to exit threads

Unified/checkor.py, utils.py
this will include an unlocking lock trace in the DB, so that the dead process can take care of it
@sharad1126
=> Non locking module check

JIRAClient.py, Unified/checkor.py, Unified/closor.py
not to be merged yet.
this is the branch that can be worked on to create JIRA from unified.
=> Creating JIRA from unified

JIRAClient.py, Unified/actor.py
this will update the comments of the jira with the workflow prepid in the summary ; one comment per task might be a lot. we'll see with experience @sharad1126
=> actor updating comments in JIRA

JIRAClient.py, Unified/htmlor.py
this is the alpha version. there needs to be some veto on setting a JIRA.
Heartbeat ? find a time over which to make the JIRA maybe ?
Components in auto-restart ? certainly not. Which are they ?
@scarletnorberg
=> Creating JIRA for agent error

wtcActions.py
#364 instructions added in comment
=> instructions for the script added

wtcActions.py
=> Wtcactions script running instructions

Unified/htmlor.py, Unified/remainor.py, utils.py
=> information about dataset remaining at sites in mongodb

Unified/addHoc.py, Unified/checkor.py, Unified/closor.py, Unified/completor.py, Unified/equalizor.py, Unified/htmlor.py, Unified/injector.py, Unified/invalidator.py, Unified/lockor.py, Unified/recoveror.py, Unified/rejector.py, Unified/subscribor.py, Unified/transferor.py, utils.py
From the current outing of JIRA, modules are failing.
should it be a soft or hard check is the question @sharad1126 @drkovalskyi
=> check on jira

JIRAClient.py, Unified/completor.py, Unified/htmlor.py
for #384 . With  
```
jira_priority_and_delays = { 11000 : 14,
90000 : 21}
```
it is going to make a jira for wf with prior>=110k after 14 days, >= 90 after 21days, and nothing else.
With
`         ping_on_jira = 7 *(24*60*60) # 7 days `
it will insert a new comment every 7 days after the last comment in the jira
=> Create JIRA for long running workflows

Unified/assignor.py, Unified/injector.py, utils.py
instead of having opened blocks in phedex dangling around
=> Closing blocks when requested for processing

utils.py
is this what you had in mind @yuyiguo #346
=> faster DBS loop

Unified/addHoc.py
@sharad1126 if you are interested
=> closing jira for inactive wf

Unified/checkor.py, utils.py
=> Check failed ACDC

Unified/rejector.py
this might turn out interesting eventually
=> multicore setup at the dictionnary base level

actcycle.sh, assigncycle.sh, cWrap.sh, clearcycle.sh, cycle_common.sh, errorcycle.sh, gqcycle.sh, logscycle.sh, postcycle-review-manual.sh, postcycle-review-recovering.sh, postcycle-strict.sh, postcycle-update.sh, precycle.sh, remainingcycle.sh, runerrorcycle.sh, shortcycle.sh, subscribecycle.sh, toperrorcycle.sh, unlockingcycle.sh, viewcycle.sh
some cleanup of the cycle scripts
@drkovalskyi @sharad1126
=> Factor cycle

utils.py
The output size should be post efficiency calculation
=> Take filter efficiency into account when splitting based on size/evt

Unified/injector.py, unifiedConfiguration.json, utils.py
Reverts CMSCompOps/WmAgentScripts#408
=> Revert "Enabling stepchain conversion."

Unified/remainor.py, utils.py
@drkovalskyi for what concerns all dataset left over in dataops by dynamo, this will clear things up little by little and will prevent from things getting there again.
@dr-stringfellow FYI
=> specific unlocked assigned to anaops

Unified/checkor.py
@thongonary can you please have a look?
=> no small lumi tag if wf is relval

Unified/closor.py
Fixes #436 
ready but nor tested
Added a flag to check 50% and then send an extra email to HN. 
yes
no
@thongonary can you please have a look?
=> sending emails to PPD HN for relvals < 50%

utils.py
<In development | not-tested >
https://cern.service-now.com/service-portal/view-incident.do?n=INC2095005
After copying the file, should check if the destination file in EOS has file size > 0, else retry
YES 
@sharad1126
=> check file stat after copying

JIRAClient.py
Fixes #454 
ready
using force-reinstall can be more effective than uninstall/install.
yes
https://github.com/CMSCompOps/WmAgentScripts/pull/455
requests package and urllib3 package
@thongonary @drkovalskyi
=> force-reinstall instead of uninstall and install

utils.py
https://its.cern.ch/jira/browse/CMSMONIT-124
ready
There were links that were reported in the above mentioned Jira. The links commented out have been mentioned by Stephan as not being updated with proper values. 
yes
N/A
no
@thongonary @drkovalskyi
=> dash-ssb links removed that are not being updated with reliable value

Unified/assignor.py, Unified/completor.py, Unified/stagor.py, utils.py
Fixes #459
ready
removed links from utils.py and other modules calling that function.
yes
N/A
no. removed dependency on a url
@thongonary @drkovalskyi
=> remove legacy link of sid from transfer team

Unified/deadlock.py, utils.py, whatjob.sh
caching of listFileArrays. all calls succeeds
=> Filearray cache

Unified/checkor.py
no need to manually make tape request if the campaign indicates a destination
=> do what the campaign says

utils.py
from @vkuznet suggestions.
working in progress
=> change of dbs apis

Unified/actor.py, utils.py
Fixes #None since none opened
ready for test
centralize dropping of parameter
y
=> stripping split parameters

Unified/actor.py, utils.py
@areinsvo @SvenjaPflitsch @prozober
=> allow to assign to all sites reading from a SE

utils.py
Fixes #364 
ready
Removes legacy code as discussed https://github.com/CMSCompOps/WmAgentScripts/pull/364#issuecomment-581863067
yes
#364 
removes afs dependency 
@z4027163
=> removed sync and getForceCompletes() functions

utils.py
Fixes #488 
tested 
The pull request migrates all json calls from dashb-ssb to grafana calls.
yes
#489 
dashb-ssb* metrics, monit-grafana
@vlimant @amaltaro @z4027163
=> Migrate dashb_ssb metrics to grafana

CondorMonitoring/JobCounter.py, Unified/htmlor.py, site_view.py, utils.py
Fixes #487 #488 
tested  
NO
#458 
dash-ssb*, dash-cms*
@z4027163 @vlimant @amaltaro
=> Remove legacy dashssb

serviceConfiguration.json, utils.py
=> Feature unified config param

Unified/actor.py, utils.py
ACDC priority change testing
Get failed job numer from wmstats
=> ACDC priority change according its size

Unified/actor.py, utils.py
ACDC priority change based on WF size, tested
Get FailedJob number from wmstats
=> ACDC priority change based on WF size

utils.py
purging of some mongo db collections
=> mongodb purge

utils.py
Reverts CMSCompOps/WmAgentScripts#522
=> Revert "mongodb purge"

utils.py
Reverts CMSCompOps/WmAgentScripts#523
=> Revert "Revert "mongodb purge""

precycle.sh
Fixes #536 
tested
This will stop running the stagor module. 
yes
#519 
stagor.py
@z4027163 @amaltaro @vlimant
=> stopping stagor module

utils.py
further on #462 #476 
affecting "only" showError.py I believe ( @z4027163 you had a recent look I think )
=> caching repetitive calls to dbs

Unified/step_chain_test.py, utils.py
Bug Fixes
ready
Fixed wrong indentation that was preventing some TaskChain requests to be converted to StepChain. Added a small script to test workflows if they are Ok to be converted.
YES
=> Bug fix for StepChain conversion

utils.py
would avoid GQ module to fail every other hour because of wmstats
FYI @amaltaro
=> stop failing on wmstats

utils.py
Reverts CMSCompOps/WmAgentScripts#568
Please do not merge yet, I just wanted to make this PR to make sure we don't forget it.
@sharad1126 @z4027163
=> Revert "Temporarily stop heavy wmstatsserver requests"

Unified/closor.py
Fixes #583 
ready
the sendLog was missing one argument. The log was not being sent to any module. 
no
#583 
elastic search instance
@amaltaro @todor-ivanov @z4027163
=> should send log to closor module

Unified/equalizor.py
Fixes #593 
Use maximum number of cores in stepchain to check the memory usage
@sharad1126
=> use maximum number of cores of stepchain to check the memory

.github/workflows/python_lint.yml
Ready
Run flake8 and pylint tests on git diff for every PR
Yes
None
None
=> run pylint on pull requests

Unified/checkor.py, unifiedConfiguration.json
solves #538 and gets further with checking independently the size of each dataset, not only the sum
=> Mss size check

Unified/checkor.py, Unified/htmlor.py, utils.py
#540 
remove phedex from component check. Add phedex check back in checkor and htmlor
@sharad1126 @vlimant
=> Remove phedex check except for checkor and htmlor

Unified/checkor.py
Fix error from mss_size_check PR
https://github.com/CMSCompOps/WmAgentScripts/pull/539
=> Fix error from mss_size_check PR

serviceConfiguration.json, utils.py
allows to run tests in testing machine using the testbed endpoints
ready
The urls in utils.py are imported from serviceconfig json file which allows to have production endpoints in master branch and testbed urls in testing branch
no
n/a
none 
@z4027163
=> add a serviceconfig file to change endpoint urls

Unified/equalizor.py, Unified/htmlor.py, Unified/showError.py, utils.py
Fixes #611 
change eos interaction with eos command.
For reading/writing/accessing/moving files in eos, add eos ENV set up and eos command.
@sharad1126
=> change eos I/O command

utils.py
Fixes #622 (Partially) 
If all the sites' available space is 0, randomly pick one of the sites, instead of picking the first of them always.
@sharad1126 @vlimant
=> Add random selection if all the sites available space is 0

Unified/checkor.py
sorry for leaving untested code in #539.
this is slightly better than #614 @z4027163 IMO
=> query once the size of output to be checked

Unified/checkor.py
Reverse PR 616, as it causes problem.
@sharad1126 @vlimant
=> reverse PR 616 (messed up PR)

JIRAClient.py, unifiedConfiguration.json
Add Hasan in unified necessary files. 
tested
Hasan replaces Sharad. 
no
n/a
Hasan
@z4027163  fyi
=> add Hasan to necessary places

Unified/rejector.py
not-tested
Add manual option to the rejector module to bypass the JIRA check
yes
none
none
@sharad1126 and @z4027163 FYI
=> Add manual option to the rejector module

unifiedConfiguration.json
not tested
Add asahasra to the relval_user list upon the request from PdmV
yes
@sharad1126
=> Add asahasra to the relval_users

unifiedConfiguration.json
not tested
Add srappocc to the relval_user list.
yes
@sharad1126 FYI
=> Add srappocc to the relval_users

Unified/assignor.py
=> Add rucio skip in assignor

Unified/checkor.py, Unified/closor.py, Unified/subscribor.py
Skip two workflows for phedex testing
=> Skip two workflows for phedex testing

Unified/checkor.py, Unified/closor.py, Unified/subscribor.py
Change test wfs from NanoAOD to GS
=> Change test wfs from NanoAOD to GS

Unified/GQ.py, Unified/checkor.py, Unified/closor.py, Unified/collector.py, Unified/spreador.py, Unified/subscribor.py, phedexClient.py
Fixes https://github.com/dmwm/WMCore/issues/9836
In development
Bare minimum changes to stop making PhEDEx requests to subscribe data.
Bare minimum changes to stop making Dynamo/DDM data placement requests.
Note that the code needs to be properly cleaned up such that CPU cycles are not spent on handling data that won't be subscribed.
no
none
none
@haozturk @z4027163
=> Remove PhEDEx/Dynamo replica requests from Unified modules

acrontab.list
not tested
Re-enable Checkor module with the new code which does not do output data placement. 
yes
#657 
@z4027163  FYI
=> Re-enable checkor module

campaigns.json
=> enable RunIISummer20UL18GEN

campaigns.json
created campaign RunIISummer20ULPrePremix
=> created campaign RunIISummer20ULPrePremix

campaigns.json
=> Adding minbais to 20ULPrePremix campaign

campaigns.json
=> Opending 20ULPrePremix

campaigns.json
=> add partial copy in RunIISummer19ULPrePremix for goodIO test

Unified/equalizor.py
Fixes #673 
not tested
As discussed in the Rucio transition meeting, we will stop overflow mechanism in Unified. If we lack without this functionality, WMCore will implement with a high priority.
yes
none
none
@z4027163 @amaltaro  FYI
=> Stop Premix, PU and Prim overflow mechanism in equalizor

Unified/checkor.py, utils.py
Remove phedex, change to rucio  for checkor.
=> change phedex to rucio

campaigns.json
Updating the campaigns that have minbais to remove the upper part of the sitewhitelist.
=> Removing the top site white list

campaigns.json
Set partial copy as 95% for RunIISummer20UL16DIGIPremix
@scarletnorberg  FYI
=> Set partial copy as 95% for RunIISummer20UL16DIGIPremix

Unified/htmlor.py
Fixes #694 
not tested
These 3 modules are not working anymore. This PR stops doing checks over them.
no
none
none
@scarletnorberg @z4027163  FYI
=> Do not check gq, stuckor and subscribor heartbeat

utils.py
Bug fix: Use set operator to avoid duplicate sites in the sitewhitelist
=> Fix duplicate site problem

utils.py
Reason:
```
[haozturk@lxplus736 ~]$ curl -s http://cms-gwmsmon.cern.ch/poolview/json/totals
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://cms-gwmsmon.cern.ch/poolview/json/totals">here</a>.</p>
</body></html>
```
=> Change gwmsmon link from http to https

campaigns.json
created 3 new campaigns, anoAODUL18Data, NanoAODUL17Data and NanoAODUL16Data
=> created NanoAODUL18Data, NanoAODUL17Data and NanoAODUL16Data

unifiedConfiguration.json
not tested
Update relval users upon request by PdmV
yes
none
none
=> Update relval users

\
Fixes https://its.cern.ch/jira/browse/PRCAMPAIGNS-82
not tested
Update secondary for Phase2HLTTDRWinter20DIGI. See the ticket for details
yes
none
none
@scarletnorberg  @z4027163  FYI
=> Update secondary for Phase2HLTTDRWinter20DIGI

campaigns.json
Updating because successful pilots 
RunIISummer20UL18MiniAODv2 JIRA 178
RunIISummer20UL17MiniAODv2 JIRA 177
RunIISummer19UL17MiniAODv2 JIRA 173
=> MiniAOD MC successful pilots

campaigns.json
True for the RunIISummer20UL17NanoAODv2 pilot finally successful
=> Opening RunIISummer20UL17NanoAODv2

utils.py
Fixes #753 
not tested
These code pieces are redundant and they lead to errors. This PR comments out them. In a later PR, we can remove them completely.
no
None
None
@z4027163  FYI
=> Remove redundant and problematic code pieces

Unified/assignor.py
=> Exclude HLT only according to primary AAA

Unified/assignor.py, utils.py
Fixes #776 
not tested
Set SiteBlacklist parameter during workflow assignment. Details: #776 
-
None
None
@todor-ivanov @amaltaro @z4027163 FYI
=> Set SiteBlacklist parameter during workflow assignment

reqMgrClient.py
Fixes #776 
not tested
In #777  I haven't realized this line of code which prevents us setting a `SiteBlacklist`. This PR removes that.
-
#777
-
=> Fix the obstacle before setting a SiteBlacklist

campaigns.json
PRCAMPAIGNS-181 and PRCAMPAIGNS-182 pilots successful
=> Adding in Run3Winter21wmLHEGS and GS version pilot successful

assistance/Workflow.py
Fixes #765 
In development
This PR provides a baseline code required to develop the filtering system described in #731. It includes the function prototypes for the bare minimum requirements.
No
None
None
@hbakhshi @z4027163  Feel free to add your suggestions here
=> Initial form of the Workflow class

campaigns.json
PRCAMPAIGNS-183 Run3Winter21DRMiniAOD adding PU 
PRCAMPAIGNS-187 SnowmassWinter21wmLHEGEN new campaign
PRCAMPAIGNS-185 SnowmassWinter21GEN new campaign
=> Adding MinBais PU and two Snowmass Campaigns

campaigns.json
Also added snowmass because merge conflict with the other PR
PRCAMPAIGNS-189
PRCAMPAIGNS-188
Adding NanoGEN for 17/18
=> Adding in NanoGen campaigns

campaigns.json
Fix typo in T1_IT_CNAF_Disk_Disk.
=> Fix typo in T1_IT_CNAF_Disk_Disk

campaigns.json
Adding pileup file PRCAMPAIGNS-82 Phase2HLTTDRWinter20DIGI
Pilot successful PRCAMPAIGNS-183 Run3Winter21DRMiniAOD
new campaign HINPbPbSpring21MiniAOD PRCAMPAIGNS-190
=> March17 update 82 183 190

campaigns.json
Turning on HINPbPbSpring21MiniAOD pilot successful
and 
Forgot to add the second site of the secondary so adding that in: Phase2HLTTDRWinter20DIGI
=> Updating secondary, and turning on a campaign

Unified/addHoc.py, Unified/assignor.py, Unified/step_chain_test.py, utils.py
Fixes #818 
not tested
Usages of all functions and classes are analyzed and all unnecessary code is removed (~3k lines of code)
no
None
None
@z4027163  FYI
=> Clean all unnecessary code in utils

campaigns.json
Adding new HI campaign HINPbPbWinter16wmLHEGSHIMix PRCAMPAIGNS-191
=> Hi april campaign

campaigns.json
PRCAMPAIGNS-192
PRCAMPAIGNS-193
PRCAMPAIGNS-194
PRCAMPAIGNS-195
PRCAMPAIGNS-196
PRCAMPAIGNS-197
PRCAMPAIGNS-198
PRCAMPAIGNS-199
PRCAMPAIGNS-200
=> Open FastSim campaigns

campaigns.json
As requested in the relevant JIRA tickets, this PR updates the secondaries for FS campaigns
=> Update FS campaign secondaries

unifiedConfiguration.json
=> Increase stepchain conversion threshold

Unified/rejector.py, unifiedConfiguration.json, utils.py
Fixes #831 
not tested
This PR updates stepchain conversion logic such that we run stepchains with 4 cores - 7900MB memory
Yes
#829 
None
@z4027163  FYI
=> Run stepchains w/ 4 cores 7900 MB memory

Unified/injector.py, unifiedConfiguration.json
Fixes #834 
not tested
Injector takes into account requests submitted by PnR users
yes
None
None
@z4027163  FYI
=> Injector takes into account taskchain requests submitted by PnR users

campaigns.json
Updating https://its.cern.ch/jira/projects/PRCAMPAIGNS/issues/PRCAMPAIGNS-191 added a pileup file HINPbPbWinter16wmLHEGSHIMix
Turned a campaign to true https://its.cern.ch/jira/projects/PRCAMPAIGNS/issues/PRCAMPAIGNS-192 the RunIISpring21UL18FSGSPremix
=> Updating the UL18FS campaign adding a pileup file

utils.py
Fixes #843 
tested
Make case insensitive check for pilots
yes
None
None
@z4027163  FYI
=> Make case insensitive check for pilots

campaigns.json
PRCAMPAIGNS-206 RunIISummer20UL16NanoAODv9
PRCAMPAIGNS-207 RunIISummer20UL16NanoAODAPVv9
PRCAMPAIGNS-208 RunIISummer20UL17NanoAODv9
PRCAMPAIGNS-209 RunIISummer20UL18NanoAODv9
PRCAMPAIGNS-210 NanoAODv9UL18Data
PRCAMPAIGNS-211 NanoAODv9UL16Data
=> Adding v9 RunIISummer20UL* and data campaigns of the same type

campaigns.json
PRCAMPAIGNS-209 pilot successful 
Would like the merge to happen a little later Monday
=> opening NanoAODv9 20UL18

campaigns.json
PRCAMPAIGNS-204
PRCAMPAIGNS-200
These two campaigns need three Minbais.
=> Adding some minbais's to various campaigns

unifiedConfiguration.json
Fixes #857
ready
Check the issue for discussion
None
None
@amaltaro  the alerts should disappear after this PR
=> Add GEN-SIM-DIGI-RAW-HLTDEBUG-RECO to tiers_to_DDM

campaigns.json
PRCAMPAIGNS-207
PRCAMPAIGNS-206
Pilots successful for 2 nanoAOD v9 MC requests
=> Two NanoAODv9 pilots successful

unifiedConfiguration.json
Fixes #862 
tested
Add T3_US_OSG in production. Check the issue for reasoning. 
None
None
@z4027163  FYI
=> Add T3_US_OSG in production

campaigns.json
PRCAMPAIGNS-210 pilot done and successful https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=ReReco-Run2018C-JetHT-UL2018_MiniAODv2_NanoAODv9_pilot-00001 this is 99.6% and no errors so should be good 
PRCAMPAIGNS-211 Pilot is totally 100% successful https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=ReReco-Run2016F-MET-UL2016_MiniAODv2_NanoAODv9_pilot-00001
Things seemed to have ran better at the end of the week than the beginning of the week.
=> campaigns.json

campaigns.json
https://its.cern.ch/jira/browse/PRCAMPAIGNS-205?orderby=updated+DESC%2C+priority+DESC
Last nanoAOD data campaign
=> Pilot done for NanoAODv9UL17Data

Unified/injector.py
Fixes #881
not tested
Pick up stepchains of pnr members automatically in Injector
yes
None
None
@z4027163  FYI
=> Pick up stepchains of pnr members automatically

campaigns.json
All the campaigns have slightly different settings and we still need a pileup file for DR 
Here are the JIRA tickets:
PRCAMPAIGNS-216
PRCAMPAIGNS-217
PRCAMPAIGNS-218
PRCAMPAIGNS-219
PRCAMPAIGNS-220
I think this should hopefully spark some discussion on what is needed in the campaigns.
=> RunIISummer20UL*pp5TeV for 2017 Adding all in slightly different way

campaigns.json
I removed the secondary locations because I thought with primary AAA it should run fine. I also forgot to open a transfer ticket but have opened one to ask about the placement of the secondary. 
PRCAMPAIGNS-192
PRCAMPAIGNS-193
PRCAMPAIGNS-194
PRCAMPAIGNS-195
PRCAMPAIGNS-196
PRCAMPAIGNS-197
https://its.cern.ch/jira/browse/CMSTRANSF-283
=> Changing pileup

campaigns.json
https://its.cern.ch/jira/browse/CMSTRANSF-296 this is the data management ticket 
PRCAMPAIGNS-200 for this campaign
=> Adding new pileup for FS that is tuneCP5

campaigns.json
=> Changing site on FS because purdue is in drain T2_US_UCSD

campaigns.json
Necessary for #924
not tested
Update partial copy of UltraLegacy2017 for testing. 
@z4027163  FYI
=> Update partial copy of UltraLegacy2017 for testing

campaigns.json
https://its.cern.ch/jira/browse/PRCAMPAIGNS-223
https://its.cern.ch/jira/browse/PRCAMPAIGNS-224
=> Enable Run3Summer21wmLHEGS and Run3Summer21GS

campaigns.json
PRCAMPAIGNS-230
PRCAMPAIGNS-232
PRCAMPAIGNS-234
RunIISpring21UL*FSGSDR
The minbais has a location based on what we requested before. I just put where I found when checking but there is no point in opening another JIRA ticket with data management. Less than 5 WF's will be used for this.
=> RunIISpring21UL*FSGSDR adding

campaigns.json
Adding Run3Summer21DR which I guess got lost. I think I thought you added it hasan but there is no pileup which again we have decided I thought that we need the pileup to test. Checking in the meeting today.
=> Run3Summer21DR adding

campaigns.json
PRCAMPAIGNS-236 Comissioning2021 pilot lumi successful number of events 93% here is github issue talking about this: https://github.com/dmwm/WMCore/issues/10568 
Still unknown.
=> Adding Commisioning2021 to true for go

campaigns.json
PRCAMPAIGNS-227 Run3Summer21PrePremix pilot successful
=> Pilot for the Run3Summer campaign went

campaigns.json
PRCAMPAIGNS-225 pileup placement pilot successful
=> Run3SummerDRPremix campaign pileup placement tested

campaigns.json
PRCAMPAIGNS-237 Run3Autumn21GS
PRCAMPAIGNS-238 Run3Autumn21wmLHEGS
PRCAMPAIGNS-239 RunIISummer20UL18GENSIM
PRCAMPAIGNS-240 RunIISummer20UL17GENSIM
PRCAMPAIGNS-241 RunIISummer20UL16GENSIMAPV
PRCAMPAIGNS-242 RunIISummer20UL16GENSIM
These are all the campaigns that wear requested.
=> Adding 4 new campaigns

campaigns.json
PRCAMPAIGNS-238 RunIISummer20UL16GENSIMAPV
PRCAMPAIGNS-239 RunIISummer20UL17GENSIM
PRCAMPAIGNS-240 RunIISummer20UL18GENSIM
PRCAMPAIGNS-237 RunIISummer20UL16GENSIM
PRCAMPAIGNS-242 Run3Autumn21GS
PRCAMPAIGNS-241 Run3Autumn21wmLHEGS
Pilots successful
=> Pilots were successful so turning campaigns to true

campaigns.json
Adding back in RunIISummer19UL17DIGIPremix
=> Adding back in RunIISummer19UL17DIGIPremix

utils.py
Fixes #964 
tested locally, works fine:
```
>>> from dbs.apis.dbsClient import DbsApi
>>> dbsApiTest = DbsApi(url = "https://cmsweb-testbed.cern.ch/dbs2go")
>>> dbsApiProd = DbsApi(url = "https://cmsweb.cern.ch/dbs/prod/global/DBSReader")
>>> 
>>> block = "/BTagMu/Run2018A-12Nov2019_UL2018-v1/AOD#325d4ec0-6554-4a27-be5c-d714232007a3"
>>> resTest = dbsApiTest.listFileLumis( block_name = block)
>>> resProd = dbsApiProd.listFileLumis( block_name = block)
>>> 
>>> resTest == resProd
False
>>> resTestAgg = aggregateListFileLumis(resTest)
>>> resProd.sort() == resTestAgg.sort()
True
>>> resTest
[{'run_num': 315543, 'lumi_section_num': 106, 'logical_file_name': '/store/data/Run2018A/BTagMu/AOD/12Nov2019_UL2018-v1/130000/7582C421-E4AD-2F42-A798-18E9331920F4.root', 'event_count': 486}, {'run_num': …
```
=> Make dbsapi.listFileLumis compatible with the upcoming DBS server

src/bash/authenticate.sh, src/bash/runner.sh, src/python/Databases/Oracle/OracleClient.py, src/python/Services/McM/McMClient.py, src/python/Unified/Injector.py, src/python/Unified/Rejector.py, src/python/Utilities/DataTools.py, src/python/Utilities/WebTools.py, src/python/WorkflowMgmt/WorkflowSchemaHandlers/TaskChainWfSchemaHandler.py
Fixes #959 
in development
To be listed
=> Deploy Invalidator in production

campaigns.json
PRCAMPAIGNS-266
PRCAMPAIGNS-265
=> Adding two new campaigns and updating some pileup

unifiedConfiguration.json
@haozturk PR for adding tyjyang to authorizing bypasses
=> Add tyjyang to authorizing bypasses

campaigns.json
PRCAMPAIGNS-266 pilot successful
PRCAMPAIGNS-265 pilot successful
=> Turning go from false to true for two successful pilots

campaigns.json
PRCAMPAIGNS-267
PRCAMPAIGNS-268
PRCAMPAIGNS-269
PRCAMPAIGNS-270
PRCAMPAIGNS-271
PRCAMPAIGNS-272
PRCAMPAIGNS-249 pilot succesful
I also did run the jq . campaigns.json check
=> Adding three new FS campaigns

campaigns.json
[PRCAMPAIGNS-255](https://its.cern.ch/jira/browse/PRCAMPAIGNS-255)
[PRCAMPAIGNS-256](https://its.cern.ch/jira/browse/PRCAMPAIGNS-256)
The pilots were successful so turned go to true.
=> Campaigns pilot successful

campaigns.json
Adding pileup
[CMSTRANSF-342](https://its.cern.ch/jira/browse/CMSTRANSF-342)
[PRCAMPAIGNS-227](https://its.cern.ch/jira/browse/PRCAMPAIGNS-227)
[PRCAMPAIGNS-257](https://its.cern.ch/jira/browse/PRCAMPAIGNS-257)
Will send email to Stephen Lemmel as well.
=> Adding the new pileup to two campaigns

campaigns.json
[PRCAMPAIGNS-280](https://its.cern.ch/jira/browse/PRCAMPAIGNS-280)
=> Adding a HIN campaign

campaigns.json
Fixing Run3Winter22DR [PRCAMPAIGNS-257](https://its.cern.ch/jira/browse/PRCAMPAIGNS-257)
And then changing Run3SummerPrePremix to FNAL
=> Changing sites and moving pileup campaign

campaigns.json
[PRCAMPAIGNS-274](https://its.cern.ch/jira/browse/PRCAMPAIGNS-274)
Pilot successful
=> Pilot was successful

unifiedConfiguration.json
Adding `fuyan` to the bypass list
@haozturk
=> Adding one user to the bypass list

campaigns.json
All I did was move around information that was in the file. Every pileup already had a site weather it is at that site or not is a different question. 
I also changed all neutrino to SecondaryLocation and minbias to SiteWhitelist
=> Neutrino to secondarylocation Minbias to SiteWhitelist

campaigns.json
[PRCAMPAIGNS-263](https://its.cern.ch/jira/browse/PRCAMPAIGNS-263) pilot successful
=> Pilot successful

campaigns.json
[PRCAMPAIGNS-262](https://its.cern.ch/jira/browse/PRCAMPAIGNS-262)
[PRCAMPAIGNS-263](https://its.cern.ch/jira/browse/PRCAMPAIGNS-263)
Pilots again successful
=> Adding back the Commissioning900* campaigns

campaigns.json
[PRCAMPAIGNS-281](https://its.cern.ch/jira/browse/PRCAMPAIGNS-281)
[PRCAMPAIGNS-282](https://its.cern.ch/jira/browse/PRCAMPAIGNS-282)
[PRCAMPAIGNS-283](https://its.cern.ch/jira/browse/PRCAMPAIGNS-283)
Adding FS campaigns without removing the ones that do not work
=> Addinf more FS without closing FS that do not work

utils.py
Fixes #1002 
tested
Remove agent config check while getting available sites - just rely on SSB
none
no new dependency
@z4027163  FYI
=> Remove agent config check while getting available sites - just rely on SSB

Unified/checkor.py
Fixes #1006 
ready
Create JIRA tickets for every workflow ending up in assistance-manual
yes
None
No new dependency
@tyjyang @z4027163 @jenimal  FYI
=> Create JIRA tickets for every workflow ending up in assistance-manual

campaigns.json
[PRCAMPAIGNS-284](https://its.cern.ch/jira/browse/PRCAMPAIGNS-284) This is the new HIN pLHE campaign requested. 
Still waiting on pilot for FS that were opened last week.
=> Adding a new campaign for HIN Run3

campaigns.json
Four campaigns have successful pilots:
[PRCAMPAIGNS-284](https://its.cern.ch/jira/browse/PRCAMPAIGNS-284) Run3Winter22PbPbpLHE
[PRCAMPAIGNS-281](https://its.cern.ch/jira/browse/PRCAMPAIGNS-281) RunIISpring22UL18FSwmLHEGSPremix
[PRCAMPAIGNS-282](https://its.cern.ch/jira/browse/PRCAMPAIGNS-282) RunIISpring22UL17FSwmLHEGSPremix
[PRCAMPAIGNS-283](https://its.cern.ch/jira/browse/PRCAMPAIGNS-283)RunIISpring22UL16FSwmLHEGSPremix
Did run the check on format.
=> 4 pilots successful including the FS and a HI campaign

Unified/actor.py
Fixes #1010 
ready
Drop SE_to_CE mapping in ACDC site assignment
yes
No
No
=> Drop SE_to_CE mapping in ACDC site assignment

campaigns.json
[PRCAMPAIGNS-286](https://its.cern.ch/jira/browse/PRCAMPAIGNS-286)
[PRCAMPAIGNS-285](https://its.cern.ch/jira/browse/PRCAMPAIGNS-285)
Two campaigns ask to be added.
=> Adding 2 campaigns

recoverMissingLumis.py
Fixes #1014 
ready
Update recovery script according to new dbs server
https://github.com/CMSCompOps/WmAgentScripts/pull/966
New DBS Server
@z4027163  fyi
=> Update recovery script according to new dbs server

campaigns.json
Pilot was successful [PRCAMPAIGNS-285](https://its.cern.ch/jira/browse/PRCAMPAIGNS-285)
=> One campaign pilot was successessful

unifiedConfiguration.json
Fixes #738 
ready
Add T2_PT_NCG_Lisbon to the goodAAA list
yes
none
no
@z4027163  fyi
=> Add T2_PT_NCG_Lisbon to the goodAAA list

campaigns.json
This looks like a lumi miss match but other wise good turning it to true? https://cms-unified.web.cern.ch/cms-unified/showlog/?search=task_PPD-Run3Winter22CosmicGS-00001
This one same thing https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_PPD-Run3Winter22CosmicGS-00001
[PRCAMPAIGNS-292](https://its.cern.ch/jira/browse/PRCAMPAIGNS-292)
[PRCAMPAIGNS-291](https://its.cern.ch/jira/browse/PRCAMPAIGNS-291)
[PRCAMPAIGNS-287](https://its.cern.ch/jira/browse/PRCAMPAIGNS-287)This pilot is 100% successful.
=> Changing three campaigns to true

unifiedConfiguration.json
ready
added myself (llavezzo) to allowed_bypass
yes
NA
NA
@haozturk
=> added myself (llavezzo) to allowed_bypass

campaigns.json
[PRCAMPAIGNS-293](https://its.cern.ch/jira/browse/PRCAMPAIGNS-293) adding in new campaign
=> Adding in another Run3 campaign

unifiedConfiguration.json
Ready
Adding my name to the bypass as requested in https://gitlab.cern.ch/haozturk/production-and-reprocessing-documentation/-/blob/master/new_devoperator_setup.md
Yes
@haozturk
=> adding madamec to bypass

unifiedConfiguration.json
ready
Adding wjang to the allowed_bypass list
YES
X
X 
@haozturk
=> Add wjang to allowed_bypass

campaigns.json
https://its.cern.ch/jira/browse/PRCAMPAIGNS-294
Adding in New campaign
=> Adding in Run3Winter22NanoAOD

archive_campaigns.json, campaigns.json
[PRCAMPAIGNS-295](https://its.cern.ch/jira/browse/PRCAMPAIGNS-295)
[PRCAMPAIGNS-298](https://its.cern.ch/jira/browse/PRCAMPAIGNS-298)
[PRCAMPAIGNS-297](https://its.cern.ch/jira/browse/PRCAMPAIGNS-297)
[PRCAMPAIGNS-300](https://its.cern.ch/jira/browse/PRCAMPAIGNS-300)
In this one "This is the correct Nano campaign. Please close the previous  https://its.cern.ch/jira/browse/PRCAMPAIGNS-287 ." hence the archive.
[PRCAMPAIGNS-306](https://its.cern.ch/jira/browse/PRCAMPAIGNS-306)
[PRCAMPAIGNS-296](https://its.cern.ch/jira/browse/PRCAMPAIGNS-296) This pilot is finished
Also one archived campaign https://its.cern.ch/jira/browse/PRCAMPAIGNS-287
=> Adding in some new campaigns that got lost from my radar

campaigns.json
=> Turning a campaign true

campaigns.json
[PRCAMPAIGNS-299](https://its.cern.ch/jira/browse/PRCAMPAIGNS-299) Run3Summer22MiniAODv3
[PRCAMPAIGNS-311](https://its.cern.ch/jira/browse/PRCAMPAIGNS-311) RunIILowPUSummer20UL17GEN
[PRCAMPAIGNS-312](https://its.cern.ch/jira/browse/PRCAMPAIGNS-312) RunIILowPUSummer20UL17SIM
[PRCAMPAIGNS-289](https://its.cern.ch/jira/browse/PRCAMPAIGNS-289) PhaseIISpring22wmLHEGS
=> New campaigns, adding a few true

campaigns.json
[PRCAMPAIGNS-289](https://its.cern.ch/jira/browse/PRCAMPAIGNS-289)
=> Pilot finished

campaigns.json
[PRCAMPAIGNS-302](https://its.cern.ch/jira/browse/PRCAMPAIGNS-302) lowpu campaign pilot success
[PRCAMPAIGNS-311](https://its.cern.ch/jira/browse/PRCAMPAIGNS-311)
[PRCAMPAIGNS-301](https://its.cern.ch/jira/browse/PRCAMPAIGNS-301)
[PRCAMPAIGNS-295](https://its.cern.ch/jira/browse/PRCAMPAIGNS-295)
[PRCAMPAIGNS-297](https://its.cern.ch/jira/browse/PRCAMPAIGNS-297)
=> Adding some new campaigns that the pilots are done

Unified/checkUnifiedStatus.py
Introduce a script which checks unified status of a given list of workflows
=> Introduce a script which checks unified status of a given list of workflows

campaigns.json
JIRA-306 Run3Winter22SIM pilot successful
=> Run3Winter22Sim successful

Unified/assignor.py, assigncycle.sh, unifiedConfiguration.json
Fixes #1051 
tested locally
Introduce a limitation to the workflow assignment to keep the total number of acquired workflows under a limit
None
We get the total number of workflows in acquired from ReqMgr
@z4027163 FYI
=> IIntroduce a limitation to the workflow assignment to keep the total number of acquired workflows under a limit

campaigns.json
@haozturk I added in the campaigns Kirill requested. Could you check if they are okay? Thanks!
=> phaseII spring22 gen and sim campaigns

campaigns.json
@z4027163 adding MB for Run3Summer21PrePremix per Bugra's request, could you approve it?
=> add MB input for Run3Summer21PrePremix

campaigns.json
Hi @z4027163, PR to be reviewed for [this](https://its.cern.ch/jira/browse/PRCAMPAIGNS-316) ticket
=> adding campaign Run3Winter22NanoAODv10

campaigns.json
@z4027163 adding new campaign from [this](https://its.cern.ch/jira/browse/PRCAMPAIGNS-317) ticket
=> PromptNanoAODv10

campaigns.json
@z4027163 adding new campaign for [this](https://its.cern.ch/jira/browse/PRCAMPAIGNS-318) ticket
=> adding Run3Winter22wmLHEGEN

campaigns.json
@z4027163 @haozturk new campaign for [this](https://its.cern.ch/jira/browse/PRCAMPAIGNS-319) ticket
=> adding Run3Winter22GEN

campaigns.json
@haozturk @z4027163 ticket [here](https://its.cern.ch/jira/browse/PRCAMPAIGNS-317)
=> enabling PromptNanoAODv10

campaigns.json
enabling Run3Winter22GEN for [this](https://its.cern.ch/jira/browse/PRCAMPAIGNS-319) ticket @haozturk @z4027163
=> enabling Run3Winter22GEN

campaigns.json
@haozturk @z4027163 Per request from [this](https://its.cern.ch/jira/browse/PRCAMPAIGNS-298) and [this](https://its.cern.ch/jira/browse/PRCAMPAIGNS-297) ticket
=> adding secondary for Run3Summer22DRPremix and Run3Summer22DR

campaigns.json
@haozturk @z4027163 Per request from [this](https://its.cern.ch/jira/browse/PRCAMPAIGNS-318) ticket
=> enabling Run3Winter22wmLHEGEN

Unified/assignor.py, unifiedConfiguration.json
Fixes #1068 
tested locally
Update workflow count more often in pending workflow check
yes
None
No new dependency
@z4027163 @tyjyang fyi
=> Update workflow count more often in pending workflow check

McMClient.py, Unified/assignSession.py, actcycle.sh, cWrap.sh, cycle_common.sh, utils.py
Fixes #1075
In development
Migrate module Unified/actor
no
None
No new dependency
@z4027163
=> WIP: Migrate module Unified/actor

campaigns.json
@haozturk @z4027163 adding campaign per [this](https://its.cern.ch/jira/browse/PRCAMPAIGNS-320) ticket.
=> adding Run3ReReco

campaigns.json
@haozturk @z4027163 for tickets:
- https://its.cern.ch/jira/browse/PRCAMPAIGNS-321
- https://its.cern.ch/jira/browse/PRCAMPAIGNS-322
- https://its.cern.ch/jira/browse/PRCAMPAIGNS-323
=> adding 2022Commission[MiniAOD|DR|GS]

campaigns.json
@haozturk For [this](https://its.cern.ch/jira/browse/PRCAMPAIGNS-320) ticket
=> enabling Run3ReReco

Unified/closor.py, closor_cycle.sh, unifiedConfiguration.json
Fixes #1081 
ready
Migrate Unified/closor to py3
=> Migrate Unified/closor to py3

campaigns.json
For tickets:
- https://its.cern.ch/jira/browse/PRCAMPAIGNS-324
- https://its.cern.ch/jira/browse/PRCAMPAIGNS-325
- https://its.cern.ch/jira/browse/PRCAMPAIGNS-326
- https://its.cern.ch/jira/browse/PRCAMPAIGNS-327
@haozturk @z4027163
=> enabling campaigns Commission22[GS|DR|MiniAOD]

campaigns.json
@haozturk for [this](https://its.cern.ch/jira/browse/PRCAMPAIGNS-325) ticket
=> adding secondary for Commission22DR

resubmit.py
Make ScramArch optional in resubmit.py
=> Make ScramArch optional in resubmit.py

campaigns.json
=> changing fractionpass to 0.95 for Commission22* campaigns

campaigns.json
@haozturk as requested in [this](https://its.cern.ch/jira/browse/PRCAMPAIGNS-329) ticket
=> adding secondaries for campaign Phase2Fall22DRMiniAOD

unifiedConfiguration.json, utils.py
Fixes #1103
ready
Remove output size correction logic in splitting check
@z4027163 fyi
=> Remove output size correction logic in splitting check

campaigns.json
@haozturk For https://its.cern.ch/jira/browse/PRCAMPAIGNS-336
=> enabling Run3Summer22EENanoAODv11

campaigns.json
@haozturk As requested by https://its.cern.ch/jira/browse/PRCAMPAIGNS-337
=> enabling Run3Summer22NanoAODv11

Unified/completor.py, completor_cycle.sh, unifiedConfiguration.json
Fixes #1111 
ready
Migrate Unified/completor.py 
no new dependency
@z4027163
=> Migrate Unified/completor.py 

campaigns.json
Per requests from:
https://its.cern.ch/jira/browse/PRCAMPAIGNS-340
https://its.cern.ch/jira/browse/PRCAMPAIGNS-341
https://its.cern.ch/jira/browse/PRCAMPAIGNS-342
https://its.cern.ch/jira/browse/PRCAMPAIGNS-343
@haozturk
=> adding Run3Winter23[GS|wmLHEGS|Digi|DigiPremix]

campaigns.json
=> T2_CH_CERN_HLT is splitting into T2_CH_CERN_HLT and T2_CH_CERN_P5

campaigns.json
=> adding PU + adding campaign + removing CSCS from el8 blacklist

campaigns.json
=> adding campaign Run3Winter23Reco

campaigns.json
=> adding campaign GenericNoSmearGEN

campaigns.json
=> enabling campaign Run3Winter23Reco

campaigns.json
@haozturk Per request in [this](https://its.cern.ch/jira/browse/PRCAMPAIGNS-342) ticket
=> enabling campaign Run3Winter23Digi

Unified/checkor.py, Unified/lumi_plot.py, Unified/lumi_summary.py
- converted lumi_plot.py to py3
- converted lumi_summary.py to py3
=> Some checkor fixes

Unified/checkor.py, Unified/createLogDB.py, Unified/showError.py, unifiedConfiguration.json
-  Lower max_per_round of checkor to 10 for debugging 
-  Introduce timeout for checkor threads: 5 mins 
-  Introduce timeout for showError threads: 5 mins 
-  Don't wait for createLogDB locks
=> 23 fix (GL)

campaigns.json
@haozturk Per [this](https://its.cern.ch/jira/browse/PRCAMPAIGNS-314) ticket
=> enabling PhaseIISpring22pLHEGEN

campaigns.json
=> enabling PhaseIISpring22SIM

recoverRereco.py
Added script to find all stuck (exitCode = -2) rereco workflows in AMR and submit a recovery.
=> Recover rereco

utils.py
=> Start pushing data to the new opensearch instance

campaigns.json
@haozturk @z4027163 Per request in [this](https://its.cern.ch/jira/browse/PRCAMPAIGNS-350) and [this](https://its.cern.ch/jira/browse/PRCAMPAIGNS-351) ticket.
=> adding campaign Run3Summer22[EE]pLHEGS

campaigns.json
@haozturk @z4027163 Per request in [this](https://its.cern.ch/jira/browse/PRCAMPAIGNS-351) ticket
=> enabling campaign Run3Summer22EEpLHEGS

campaigns.json
Hi @haozturk @z4027163, per request from [this](https://its.cern.ch/jira/browse/PRCAMPAIGNS-350) ticket
=> enabling campaign Run3Summer22pLHEGS

MSPileupClient.py, Unified/assignor.py
Create pileup documents for relval automatically during assignment
=> Create pileup documents for relval automatically during assignment

unifiedConfiguration.json
I add my name in Jira list.
I worked based on python3-migration-fast brach. So only a few lines are changed.
<YES | NO>
Hassan
=> JIRA bypass list update based on python3-migration-fast - add Piljun

campaigns.json
=> restore keepOnDisk and fractionOnDisk for deleted PU; change all SiteWhitelist to SecondaryLocation for PREMIX PUs

campaigns.json
=> fixing campaign name for HINPbPbAutumn22MiniAOD

autoACDC/runner.py
Addressing https://gitlab.cern.ch/CMSToolsIntegration/operations/-/issues/48
=> Fix 48 (GL issue)

campaigns.json
@z4027163 @jenimal @haozturk 
For ticket: https://its.cern.ch/jira/browse/PRCAMPAIGNS-358
=> enabling Run3Summer22EEwmLHENanoGEN

syncCouchDB.py
@z4027163 @jenimal please review and merge, thanks!
=> script to do couchDB sync in one go

campaigns.json
Per requests in tickets:
- https://its.cern.ch/jira/browse/PRCAMPAIGNS-371
- https://its.cern.ch/jira/browse/PRCAMPAIGNS-372
=> adding Run3Summer23NanoAODv12 Run3Summer23MiniAODv4

campaigns.json
Per requests in tickets:
- https://its.cern.ch/jira/browse/PRCAMPAIGNS-373
- https://its.cern.ch/jira/browse/PRCAMPAIGNS-374
=> adding Phase2Spring23[ECal]DIGIRECOMiniAOD

campaigns.json
@z4027163 @jenimal Needed for [this](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_SUS-RunIIFall17FSPrePremix-00002) workflow
=> adding secondary for RunIIFall17FSPrePremix

campaigns.json
=> fixing secondary info for RunIIFall17FSPrePremix

campaigns.json
Per request in ticket: https://its.cern.ch/jira/browse/PRCAMPAIGNS-375
=> adding campaign HINPbPbAutumn22wmLHEGS

campaigns.json
Per requests in tickets:
- https://its.cern.ch/jira/browse/PRCAMPAIGNS-378
- https://its.cern.ch/jira/browse/PRCAMPAIGNS-379
- https://its.cern.ch/jira/browse/PRCAMPAIGNS-380
- https://its.cern.ch/jira/browse/PRCAMPAIGNS-381
- https://its.cern.ch/jira/browse/PRCAMPAIGNS-375
- https://its.cern.ch/jira/browse/PRCAMPAIGNS-373
=> add and enable campaigns

campaigns.json
@z4027163 
1. Enable HINPbPbSpring23GSHIMix [1]
2. Enable Run3Summer23DR [2], Run3Summer23MiniAODv4 [3] and Run3SummerNanoAODv12 [4], pilot is [5]
[1] https://its.cern.ch/jira/projects/PRCAMPAIGNS/issues/PRCAMPAIGNS-376
[2] https://its.cern.ch/jira/projects/PRCAMPAIGNS/issues/PRCAMPAIGNS-369
[3] https://its.cern.ch/jira/projects/PRCAMPAIGNS/issues/PRCAMPAIGNS-371
[4] https://its.cern.ch/jira/projects/PRCAMPAIGNS/issues/PRCAMPAIGNS-372
[5] https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_PPD-Run3Summer23DR-00006
=> Enable HINPbPbSpring23GSHIMix and Run3Summer23[DR|MiniAODv4|NanoAODv12]

campaigns.json
Per request in ticket: https://its.cern.ch/jira/browse/PRCAMPAIGNS-383
=> add campaign RunIISummer20UL16wmLHENanoGENpruned

campaigns.json
Per request in ticket: https://its.cern.ch/jira/browse/PRCAMPAIGNS-353
=> add secondary for campaign HINPbPbAutumn22DR

campaigns.json
=> update el8 blacklist to include T2_UA_KIPT
